Squashed 'mod/advise/' changes from a2708615..a065b5af
a065b5af feat(main): add log for Failed gen advise
d68a1d84 feat(main): add log for Failed gen advise
c470d9bc feat(main): add log for Failed gen advise
5286f71a fix(latest): remove 2>/dev/null
9b3d1bbb fix(all): add log for complete generation
68690902 fix(advise): advise on the problem of option completion, mistakenly treating flag as an option with a parameter
6cc50423 ...
1faf29be ...
cddee6e1 ...
54565574 ...
1c8cd70d ...
cf9c773a ...
448bab6a ...

git-subtree-dir: mod/advise
git-subtree-split: a065b5af12313c1f0a49a190dde1d4569c89a9d4

diff --git a/latest b/latest
--- a/latest
+++ b/latest
@@ -3,7 +3,7 @@
 
 
 if [ -z "${ZSH_VERSION}${BASH_VERSION}" ]; then
-    x log info "advise is only available in 'bash' or 'zsh'."
+    x:info "advise is only available in 'bash' or 'zsh'."
 else
 
 ___X_CMD_ADVISE_TMPDIR="${TMPDIR%/}/.x-cmd/advise_auto_json"
@@ -219,10 +219,13 @@ ___advise_main(){
         local filepath=$tmp_filepath
         if [ ! -f "$filepath" ]; then
             local content
-            content="$(X_CMD_ADVISE_FUNC_NAME=$func eval "$func" _x_cmd_advise_json 2>/dev/null)"
-            if [ $? = 126 ]; then
+            x:debug "Start gen advise for $func"
+            content="$(X_CMD_ADVISE_FUNC_NAME=$func "$func" _x_cmd_advise_json)"
+            if [ $? -eq 126 ]; then
                 printf "%s" "$content" >"$filepath"
+                x:debug "Finished gen advise for $func"
             else
+                x:error "Failed gen advise $func : you should define _x_cmd_advise_json correctly in your function."
                 return 0
             fi
         fi
