Squashed 'mod/log/' changes from cff9a19..386c189
386c189 ...
21ae9e4 ...
7e801be Merge branch 'main' of github.com:x-bash/log
22a54b9 ...
bd3b1bb fix(log): ___x_cmd_log_init0_inner shift $1
b04d515 ...
82fd8ee ...
307c4ca ...
9dc8600 ...
2ec1bce ...
e104df9 ...
954e940 ...
f1cfe1a ...
25c2a2e ...
63dfbc8 ...
571a70e ...
15e349e ...
0d30f98 ...
41eff97 ...
ffe188a ...
694561c ...
35acc1d ...
8f6f778 ...
2f35564 ...
5885ac0 ...
f8447f7 ...
04f626d ...
b6c69c4 ...
b11b4f1 ...
77f983c ...
cf53c9f ...
d862595 ...
00313c0 ...
2db68b5 ...
ccdbc1f ...
361d393 ...
9dd5f16 ...
198f9fc ...
ffc0c0a ...
f5a39c1 ...
866bbb3 ...
084b533 ...
94f0883 ...
619a652 ...
9e22fe4 ...
5a1091c ...
445ff85 ...
4a9be5d ...
1df9d8d Remove ___x_cmd_log_set_logger_level
ad09857 ...
13b5e34 ...
18da334 ...
62976db ...
ee27341 ...
f866ae3 ...
56ce595 ...
edf4c37 ...
98e0d6f ...
febd4b7 ...
78060ea ...
83a9ad7 ...
c211a85 ...
0bc180b ...
74a1405 ...
5cfa8e9 ...
97096ab ...
82fd9c9 ...
f92c6b2 ...
9284de7 ...
89e81a3 ...
69e6587 ...
d48ea9f ...
a8600cb ...
4da81bb ...
68b31b0 ...
338aeb4 ...
4c100b3 ...
aef3079 ...
de3434c ...
0ea32ec ...
32f7780 ...
b98c9a3 ...
bac2e61 style(log): update style for warn and error msg
3aa5424 style(log): update log color format
99630d7 fix(log): fix init log return code zero

git-subtree-dir: mod/log
git-subtree-split: 386c1897deecd80594f0f92841dbf359a1f85aff

diff --git a/latest b/latest
--- a/latest
+++ b/latest
@@ -1,199 +1,297 @@
 # shellcheck shell=sh disable=SC3043 # xrc
 # author:       Li Junhao           l@x-cmd.com
 
-# Section: log main
 ___x_cmd_log() {
-    if [ $# -eq 0 ]; then
-        ___x_cmd_log -h
-        return
-    fi
-
     case "$1" in
-        help|-H|-h|--help)
-            ___x_cmd_log_help
-            return 1 ;;
-        init)
-            [ $# -gt 0 ] && shift
-            ___x_cmd_log_init "$@"
-            return ;;
-        timestamp)
-            [ $# -gt 0 ] && shift
-            ___x_cmd_log_timestamp "$@"
-            return ;;
+        :*)                                     ___x_cmd_log_pr "$@" ;;
+        "")                                     ___x_cmd_log_help; return 1 ;;
+        help|-H|-h|--help)          shift;      ___x_cmd_log_help; return 1 ;;
 
-    esac
+        init)                       shift;      ___x_cmd_log_init "$@" ;;
+        init1)                      shift;      ___x_cmd_log_init1 "$@" ;;
 
-    local level
-    local level_code
-    local var
-    while [ $# -gt 0 ]; do
-        case "$1" in
-            -*)
-                logger="${1#-}"
-                ___x_cmd_log_set_level "$logger" info 1
-                ;;
-            +*)
-                logger="${1#+}"
-                ___x_cmd_log_set_level "$logger" debug 0
-                ;;
-            *)
-                level="${1#*/}"
-                logger="${1%/*}"
-                case "$level" in
-                    debug|dbg|verbose|v)        level=debug;    level_code=0 ;;
-                    info|INFO|i)                level=info;     level_code=1 ;;
-                    warn|WARN|w)                level=warn;     level_code=2 ;;
-                    error|ERROR|e)              level=error;    level_code=3 ;;
-                    none|n|no)                  level=none;     level_code=4 ;;
-                    *)                          level=debug;    level_code=0 ;;
+        init0)                      shift;      ___x_cmd_log_init0 "$@" ;;
+        init01)                     shift;      ___x_cmd_log_init01 "$@" ;;
+        init02)                     shift;      ___x_cmd_log_init02 "$@" ;;
+
+        redirect)                   shift;      ___x_cmd_log_redirect "$@" ;;
+
+        timestamp)                  shift;      ___x_cmd_log_timestamp "$@" ;;
+        view)                       shift;      ___x_cmd_log_view "$@" ;;
+        *)
+            while [ "$#" -gt 0 ]; do
+                case "$1" in
+                    */*)                        ___x_cmd_log_set_level "${1%/*}" "${1#*/}" ;;
+                    +*)                         ___x_cmd_log_set_level "${1#+}" debug ;;
+                    -*)                         ___x_cmd_log_set_level "${1#-}" info ;;
+                    *)                          ___x_cmd_log_set_level "$1" info
                 esac
-                ___x_cmd_log_set_level "$logger" "$level" "$level_code"
-        esac
-        shift
-    done
+                shift
+            done
+    esac
 }
-# EndSection
 
-# Section: init set_level help
+# Section: init regular log
+
+# Application Module
+
+___x_cmd_log_init1(){
+    ___x_cmd_log_init_inner "$@" 1
+}
 
 ___x_cmd_log_init(){
-    local logger_name="${1}"
-
-    local var="___X_CMD_LOG_LEVEL_OF_LOGGER_${logger_name}"
-    eval "${logger_name}_log(){     O=$logger_name ___x_cmd_log_logger_func \"\$@\";   }"
-    O="No Printf" ___x_cmd_log_set_level "$logger_name" info 1
+    ___x_cmd_log_init_inner "$@" 1 2 3 4
 }
 
-___x_cmd_log_timestamp(){
-    local arg="${1:?Provide timestamp}"
-    case "$arg" in
-        on)     ___X_CMD_LOG_LOGGER_TIMESTAMP_FORMAT="+%H:%M:%S";      return 0   ;;
-        off)    ___X_CMD_LOG_LOGGER_TIMESTAMP_FORMAT= ;                return 0   ;;
-        *)      printf "Try customized timestamp format wit date command:\n"
-                if date "$arg"; then
-                    ___X_CMD_LOG_LOGGER_TIMESTAMP_FORMAT="$arg"
-                    return 0
-                fi
-                return 1    ;;
+___x_cmd_log_init_inner(){
+    local logger_name="${1:?Provide logger name}"
+    shift
+
+    local var="___X_CMD_LOG__$logger_name"
+
+    eval "$var=\${$var:-2}"
+    eval "___X_CMD_LOG__0_$logger_name="
+
+    # deprecated
+    eval "${logger_name}_log(){     ___x_cmd_log_pr $logger_name \"\$@\";   }"
+
+    local level_name
+    for level_code in 1 2 3 4; do
+        level_name="$(___x_cmd_log_level_code2name "$level_code")"
+        eval "alias ${logger_name}:$level_name='test $level_code -lt \"\${___X_CMD_LOG__${logger_name}:-2}\" || O=${logger_name} ___x_cmd_log_pr_${level_name}'"
+    done
+}
+
+# EndSection
+
+
+# Section: redirect view
+
+___x_cmd_log_redirect(){
+    local folder="$___X_CMD_ROOT_TMP/log/$$"
+    mkdir -p "$folder"
+    "$@" 2>"$folder/$(date +%s)"
+}
+
+___x_cmd_log_view(){
+    awk -f "$___X_CMD_ROOT_MOD/log/lib/view.awk"
+}
+
+# EndSection
+
+# Section: zero cost log
+
+# DEBUG + INFO + WARN + ERROR: For those module
+___x_cmd_log_init0(){
+    ___x_cmd_log_init0_inner "$@" 1 2 3 4
+}
+
+# High Efficiency Module. Like str, list, dict: DEBUG
+___x_cmd_log_init01(){
+    ___x_cmd_log_init0_inner "$@" 1
+}
+
+# DEBUG + INFO
+___x_cmd_log_init02(){
+    ___x_cmd_log_init0_inner "$@" 1 2
+}
+
+___x_cmd_log_init0_inner(){
+    local logger_name="${1:?Provide logger name}"
+    shift
+    local var="___X_CMD_LOG__$logger_name"
+
+    eval "$var=\${$var:-2}"
+    eval "___X_CMD_LOG__0_$logger_name=1"
+
+    local level_target_code
+    eval level_target_code="\${$var}"
+
+    local level_code
+    local level_name
+    for level_code in "$@"; do
+        level_name="$(___x_cmd_log_level_code2name "$level_code")"
+        if [ "$level_code" -lt "$level_target_code" ]; then
+            alias "${logger_name}:${level_name}"=" : # "
+        else
+            alias "${logger_name}:${level_name}"="O=${logger_name} ___x_cmd_log_pr_${level_name}"
+        fi
+    done
+
+    eval "$var=$level_code"
+}
+
+# EndSection
+
+# Section: level
+
+___x_cmd_log_level_name(){
+    case "${1:?Provide name}" in
+        debug|info|warn|error)      printf "%s" "$1" ;;
+        *)                          printf "%s" info ;;
+    esac
+}
+
+___x_cmd_log_level_name2code(){
+    case "${1:?Provide name}" in
+        debug)      printf "%s" 1 ;;
+        info)       printf "%s" 2 ;;
+        warn)       printf "%s" 3 ;;
+        error)      printf "%s" 4 ;;
+        *)          printf "%s" 2 ;;
+    esac
+}
+
+___x_cmd_log_level_code2name(){
+    case "${1:?Provide code}" in
+        1)      printf "%s" debug ;;
+        2)      printf "%s" info ;;
+        3)      printf "%s" warn ;;
+        4)      printf "%s" error ;;
+        *)      printf "%s" info ;;
     esac
 }
 
 ___x_cmd_log_set_level(){
     local logger_name="${1:?Provide loggername}"
+
     local level="${2:?Provide level}"
-    local level_code="${3:?Provide level code}"
+    local level_code="${3}"
 
-    local var="___X_CMD_LOG_LEVEL_OF_LOGGER_${logger_name}"
-    eval "$var=$level_code"
+    level="$(___x_cmd_log_level_name "$level")"
 
-    # local level_name
-    # local on=
-    # for level_name in debug info warn error; do
-    #     [ "$level_name" = "$level" ] && on=1
-    #     if [ -z "$on" ]; then
-    #         alias "${logger_name}:${level_name}"=" : # "
-    #     else
-    #         alias "${logger_name}:${level_name}"="${logger_name}_log ${level_name}"
-    #     fi
-    # done
+    if [ -z "$level_code" ]; then
+        level_code="$(___x_cmd_log_level_name2code "$level")"
+    fi
 
-    # log init no print
-    [ -z "$O" ] && \
-        O="$logger_name" ___x_cmd_log_logger_func info "Level of logger [$logger_name] is set to [$level]"
+    local var="___X_CMD_LOG__${logger_name}"
+
+    if eval test -z "\$___X_CMD_LOG__0_$logger_name"; then
+        eval "$var=$level_code"
+    else
+        eval "$var=$level_code"
+        if [ -d "$___X_CMD_ROOT/$logger_name" ]; then
+            ___x_cmd_log_pr "${O:-$logger_name}" warn "Reload the logger by reload the module"
+            xrc:inner "$logger_name/latest"
+        fi
+    fi
+
+    # eval "$O:debug  \"Level of logger [\$logger_name] is set to [\$level]\""
+    ___x_cmd_log_pr log debug "Level of logger [$logger_name] is set to [$level]"
+}
+
+___x_cmd_log_show_level(){
+    while [ $# -gt 0 ]; do
+        printf "%s = %s\n" "$1" "$(eval ___x_cmd_log_level_code2name "\$___X_CMD_LOG__$1")"
+        shift
+    done
+}
+
+# EndSection
+
+# Section: timestamp help
+___x_cmd_log_timestamp(){
+    local arg="${1:?Provide timestamp}"
+    case "$arg" in
+        on)     ___X_CMD_LOG__TIMESTAMP_FORMAT="+%H:%M:%S" ;;
+        off)    ___X_CMD_LOG__TIMESTAMP_FORMAT= ;;
+        *)      printf "Try customized timestamp format wit date command:\n"
+                date "$arg" || return 1
+                ___X_CMD_LOG__TIMESTAMP_FORMAT="$arg"
+    esac
 }
 
 ___x_cmd_log_help(){
-    cat >&2 <<A
+    printf '%s' '
 x log     log control facility
     Usage:
         x log init [ module ]
         x log [... +module | -module | module/log-level ]
 Subcommand:
-    init <module>:                  Generate function '<module>_log'
+    init <module>:                  Generate function "<module>_log"
     timestamp < on | off | <format> >:
                                     off, default setting. shutdown the timestamp output in log
                                     on, default format is +%H:%M:%S
                                     <format>, customized timestamp format like "+%H:%M:%S", "+%m/%d-%H:%M:%S"
 Example:
-    Enable debug log for module json:
-            x log +json          or   x log json
-            x log json/verbose   or   x log json/v
-            x log json/debug     or   x log json/d
-    Dsiable debug log for module json:
-            x log -json
-            x log json/info
-A
+    Change debug log level for module json:
+            x log json/debug   or   x log +json
+            x log json/info    or   x log -json
+            x log json/warn
+            x log json/error
+'
 
 }
-
 # EndSection
 
-# Section: logger
+# Section: printer
 # TODO: To move xrc_log
-___X_CMD_LOG_COLORIZED_TF=
+___X_CMD_LOG_C_TF=
 
-___X_CMD_LOG_LOGGER_TIMESTAMP_FORMAT=      # "+%H:%M:%S"      # Enable Timestamp.
+___X_CMD_LOG__TIMESTAMP_FORMAT=      # "+%H:%M:%S"      # Enable Timestamp.
 
-___X_CMD_LOG_COLORIZED_MSG="${___X_CMD_LOG_COLORIZED_MSG:-""}"
-___X_CMD_LOG_COLORIZED_DEBUG="${___X_CMD_LOG_COLORIZED_DEBUG:-"\\033[32m"}"
-___X_CMD_LOG_COLORIZED_INFO="${___X_CMD_LOG_COLORIZED_INFO:-"\\033[36m"}"
-___X_CMD_LOG_COLORIZED_WARN="${___X_CMD_LOG_COLORIZED_WARN:-"\\033[33m"}"
-___X_CMD_LOG_COLORIZED_ERROR="${___X_CMD_LOG_COLORIZED_ERROR:-"\\033[31m"}"
+___X_CMD_LOG_C_MSG="${___X_CMD_LOG_C_MSG:-""}"
+___X_CMD_LOG_C_DEBUG="${___X_CMD_LOG_C_DEBUG:-"\\033[0;32m"}"
+___X_CMD_LOG_C_INFO="${___X_CMD_LOG_C_INFO:-"\\033[1;36m"}"
+___X_CMD_LOG_C_WARN="${___X_CMD_LOG_C_WARN:-"\\033[1;33m"}"
+___X_CMD_LOG_C_ERROR="${___X_CMD_LOG_C_ERROR:-"\\033[1;31m"}"
 
-___X_CMD_LOG_COLORIZED_TIMESTAMP_BEGIN="${___X_CMD_LOG_COLORIZED_WARN:-"["}"
-___X_CMD_LOG_COLORIZED_TIMESTAMP_END="${___X_CMD_LOG_COLORIZED_WARN:-"]"}"
+___X_CMD_LOG_C_TIMESTAMP_BEGIN="${___X_CMD_LOG_C_WARN:-"["}"
+___X_CMD_LOG_C_TIMESTAMP_END="${___X_CMD_LOG_C_WARN:-"]"}"
 
-___x_cmd_log_logger_func(){
-    local logger="${O:-DEFAULT}"
-    local level="${1:?Please provide logger level}"
-
-    local type_color="$___X_CMD_LOG_COLORIZED_DEBUG"
-    local level_code=0
-    case "$level" in
-        debug|DEBUG|verbose)    level="DBG";    shift ;;
-        info|INFO)              level="INF";    level_code=1;   type_color="$___X_CMD_LOG_COLORIZED_INFO";       shift ;;
-        warn|WARN)              level="WRN";    level_code=2;   type_color="$___X_CMD_LOG_COLORIZED_WARN";       shift ;;
-        error|ERROR)            level="ERR";    level_code=3;   type_color="$___X_CMD_LOG_COLORIZED_ERROR";      shift ;;
-        *)                      level="DBG"     ;;
+___x_cmd_log_pr(){
+    case "${2:?Provide level}" in
+        debug)      eval "test 1 -ge \"\${___X_CMD_LOG__${1#:}:-2}\"" && { local O="${1#:}"; shift 2; L=DBG C="$___X_CMD_LOG_C_DEBUG"  ___x_cmd_log_0 "$@"; } ;;
+        info)       eval "test 2 -ge \"\${___X_CMD_LOG__${1#:}:-2}\"" && { local O="${1#:}"; shift 2; L=INF C="$___X_CMD_LOG_C_INFO"   ___x_cmd_log_0 "$@"; } ;;
+        warn)       eval "test 3 -ge \"\${___X_CMD_LOG__${1#:}:-2}\"" && { local O="${1#:}"; shift 2; L=WRN C="$___X_CMD_LOG_C_WARN"   ___x_cmd_log_0 "$@"; } ;;
+        error)      eval "test 4 -ge \"\${___X_CMD_LOG__${1#:}:-2}\"" && { local O="${1#:}"; shift 2; L=ERR C="$___X_CMD_LOG_C_ERROR"  ___x_cmd_log_0 "$@"; } ;;
+        *)          eval "test 3 -ge \"\${___X_CMD_LOG__${1#:}:-2}\"" && { local O="${1#:}"; shift 1; L=INF C="$___X_CMD_LOG_C_INFO"   ___x_cmd_log_0 "$@"; } ;;
     esac
+}
 
-    local msg_color="${___X_CMD_LOG_COLORIZED_MSG:-"$type_color"}"
-    local var="___X_CMD_LOG_LEVEL_OF_LOGGER_${logger}"
+___x_cmd_log_pr_debug(){
+    L=DBG C="$___X_CMD_LOG_C_DEBUG"  ___x_cmd_log_0 "$@"
+}
 
-    eval "[ $level_code -lt \"\${${var}:-1}\" ]" && return 0
+___x_cmd_log_pr_info(){
+    L=INF C="$___X_CMD_LOG_C_INFO"  ___x_cmd_log_0 "$@"
+}
 
-    if [ -z "$___X_CMD_LOG_COLORIZED_TF" ]; then
-        if [ -t 2 ]; then
-            ___X_CMD_LOG_COLORIZED_TF=true
+___x_cmd_log_pr_warn(){
+    L=WRN C="$___X_CMD_LOG_C_WARN"  ___x_cmd_log_0 "$@"
+}
+
+___x_cmd_log_pr_error(){
+    L=ERR C="$___X_CMD_LOG_C_ERROR"  ___x_cmd_log_0 "$@"
+}
+
+___x_cmd_log_0(){
+    local IFS=" "
+    local timestamp
+
+    if [ -n "$___X_CMD_LOG_C_TF" ] || [ -t 2 ]; then
+        if [ -n "$___X_CMD_LOG__TIMESTAMP_FORMAT" ]; then
+            timestamp="$(date "${___X_CMD_LOG__TIMESTAMP_FORMAT}")"
+            timestamp="${___X_CMD_LOG_C_TIMESTAMP_BEGIN}${timestamp}${___X_CMD_LOG_C_TIMESTAMP_END} "
+        fi
+
+        if [ $# -gt 0 ]; then
+            printf "${timestamp}${C}[%s] <%s>: \033[0m${___X_CMD_LOG_C_MSG:-"$C"}%s\033[0m\n" "$L" "$O" "$*"
         else
-            ___X_CMD_LOG_COLORIZED_TF=false
-        fi
-    fi
-
-    local IFS=
-    local timestamp=
-    if [ "$___X_CMD_LOG_COLORIZED_TF" = true ]; then
-        if [ -n "$___X_CMD_LOG_LOGGER_TIMESTAMP_FORMAT" ]; then
-            timestamp="$(date "${___X_CMD_LOG_LOGGER_TIMESTAMP_FORMAT}")"
-            timestamp="${___X_CMD_LOG_COLORIZED_TIMESTAMP_BEGIN}${timestamp}${___X_CMD_LOG_COLORIZED_TIMESTAMP_END} "
-        fi
-
-        if [ $# -eq 0 ]; then
-            printf "${timestamp}\033[1m${type_color}[%s] <%s>:" "$level" "$logger"
+            printf "${timestamp}${C}[%s] <%s>:" "$L" "$O"
             cat | awk 'NR==1{ print($0) }; NR>=2{ print("> " $0); }; END{ printf("%s", "\033[0m"); }'
-        else
-            printf "${timestamp}\033[1m${type_color}[%s] <%s>: \033[0m${msg_color}%s\033[0m\n" "$level" "$logger" "$*"
         fi
     else
-        [ -n "$___X_CMD_LOG_LOGGER_TIMESTAMP_FORMAT" ] && timestamp="$(date "${___X_CMD_LOG_LOGGER_TIMESTAMP_FORMAT}") "
-        if [ $# -eq 0 ]; then
-            printf "${timestamp}[%s] <%s>:" "$level" "$logger"
-            cat | awk 'NR==1{ print($0) }; NR>=2{ print("> " $0); }; }'
+        [ -n "$___X_CMD_LOG__TIMESTAMP_FORMAT" ] && timestamp="$(date "${___X_CMD_LOG__TIMESTAMP_FORMAT}") "
+        if [ $# -gt 0 ]; then
+            printf "${timestamp}[%s] <%s>: %s\n" "$L" "$O" "$*"
         else
-            printf "${timestamp}[%s] <%s>: %s\n" "$level" "$logger" "$*"
+            printf "${timestamp}[%s] <%s>:" "$L" "$O"
+            cat | awk 'NR==1{ print($0) }; NR>=2{ print("> " $0); }; }'
         fi
     fi >&2
 }
+
 # EndSection
 
 # Section: completer, Maybe we can use advise.json to replace it for advise module can support the following function.
@@ -239,4 +337,3 @@ ___x_cmd_log_completer(){
 }
 # EndSection
 
-xrc setmain ___x_cmd_log
