Squashed 'mod/x-cmd/' changes from 5f068d89..93bb145c
93bb145c ...
8b707618 ...
b4cff00f ...
652c92e1 ...
faa14420 ...
6e82a1d5 ...
fef5d46b ...
92161eb2 ...
5e1b790e ...
e0999d69 ...
cd84ed7a ...
5c7fb98f ...
0e5a3647 ...
9ee4e4be ...
c188d97a ...
2135462a ...
28d1692f ...
a42197ec ...
a8701b8c ...
4679e39b ...
0da359af ...
01069ff1 ...

git-subtree-dir: mod/x-cmd
git-subtree-split: 93bb145c35040d3b78793294331b48470be9e24b

diff --git a/v0 b/v0
--- a/v0
+++ b/v0
@@ -60,14 +60,18 @@ ___xrc_run(){
     local ___xrc_run_filepath="${1:?filepath}";        shift
     xrc "$___xrc_run_filepath"
     local ___xrc_module_name="${___xrc_run_filepath##*/}"
-    if [ "$___xrc_module_name" = "$___xrc_module_name" ]; then
-        cat <<A
+
+    if command -v "___x_cmd_${___xrc_module_name}"; then
+        "___x_cmd_${___xrc_module_name}" "$@"
+    elif command -v "${___xrc_module_name}"; then
+        "${___xrc_module_name}" "$@"
+    else
+        cat 2>/dev/null <<A
 File not containing function: $___xrc_module_name
 Exit without execute: $___xrc_module_name "$@"
 A
         return 1
     fi
-    ___xrc_module_name "$@"
 }
 
 ___x_cmd_xrc_run()(
@@ -237,15 +241,8 @@ A
 
 # EndSection
 
-
 # Section : utilties in static-build
 xrc static-build
-
-# _x_xrc_run()(
-#     local name=$1;  shift
-#     xrc "$name"
-#     $name "$@"
-# )
 
 # _x_xrc_static_run(){
 #     local name=$1;  shift
@@ -280,117 +277,21 @@ ___x_cmd_bat(){
 
 # EndSection
 
-# Section : Runtime
+# Section : Runtime, future using xenv module
 xrc x-cmd/_v0/node
 xrc x-cmd/_v0/python
 # . _v0/node
 # . _v0/python
 
-# EndSection
-
-# Section : engine management
-
 # node: node v12 and above, x using v16
 # python: v3.6 and above, python using v14
-
 
 # EndSection
 
 # Section : xaas
-___x_cmd_notify(){
-    local msg="${1:?Provide msg}"
-    local title="${2:-""}"
-
-    # Mac
-    osascript -e "display notification \"$msg\" with title \"$title\""
-
-    # Linux
-
-    # Windows
-
-    # x-cmd service
-}
 
 # queue
 # cron
-
-# EndSection
-
-# Section : install
-
-___x_cmd_install(){
-    local subcmd="${1}";    shift
-
-    if [ -z "$subcmd" ]; then
-        ___x_cmd_install help
-        return
-    fi
-
-    case "$subcmd" in
-        help)           cat <<A
-SYMPOSIS:
-    x install <software>
-    x install ls
-    x install <get|run> <software>
-
-SUBCOMMANDS:
-    ls          list all software
-    get         get software installation command
-A
-        ;;
-        ls)             ___x_cmd_install_ls "$@" ;;
-        get)            ___x_cmd_install_get "$@" ;;
-        *)              ___x_cmd_install_run "$subcmd" "$@" ;;
-    esac
-}
-
-___x_cmd_install_run(){
-    local target
-    target="$(___x_cmd_install_get "${1:?Provide target}")"
-    printf "Executing command:\n> \e[32;1m%s\e[0m\n\n" "$target" >&2
-    eval "$target"
-}
-
-___x_cmd_install_ls(){
-    local CACHE="$___X_CMD_XRC_PATH/tmp/install/index.yml"
-    ___x_cmd_curl_gitx "x-cmd" "install/index.yml"
-    awk '
-$0!~/^#/{
-    if ($0~/^[\ ]+/) {
-        CODE = CODE "\n" $0
-    } else {
-        res = substr($0, 1, length($0)-1)
-        if (res != "") {
-            print res
-        }
-        CODE = ""
-    }
-}
-' <"$CACHE"
-
-}
-
-___x_cmd_install_get(){
-    local CACHE="$___X_CMD_XRC_PATH/tmp/install/index.yml"
-    ___x_cmd_curl_gitx "x-cmd" "install/index.yml"
-    awk -v target="${1:-Provide target}" '
-$0!~/^#/{
-    if ($0~/^[\ ]+/) {
-        CODE = CODE "\n" substr($0, 5)
-    } else {
-        if (NAME == target) {
-            CODE = substr(CODE, 2)
-            print CODE
-            exit(0)
-        }
-
-        NAME = substr($0, 1, length($0)-1)
-        CODE = ""
-    }
-}
-' <"$CACHE"
-
-}
 
 # EndSection
 
@@ -432,52 +333,30 @@ ___x_cmd_ls(){
 }
 
 
-# file upload
-# file share
-# file ls
-
-___x_cmd_hub(){
-    local subcmd=$1;    shift
-    case "$subcmd" in
-        ls)             ___x_cmd_file_ls "$@" ;;
-        upload)         ___x_cmd_file_upload "$@" ;;
-        share)          ___x_cmd_file_share "$@" ;;
-        public)         ___x_cmd_file_share "$@" ;;
-        private)        ___x_cmd_file_private "$@" ;;
-    esac
-}
-
 ___x_cmd_main(){
     local subcmd=$1;    shift 2>/dev/null
     case "$subcmd" in
-        login)                                  ___x_cmd_login "$@" ;;
-        register)                               ___x_cmd_register "$@" ;;
-        token)                                  ___x_cmd_token "$@" ;;
-        hub)                                    ___x_cmd_hub "$@" ;;
+        boot)                                   ( xrc x-cmd/_v0/boot && ___x_cmd_boot "$@"; ) ;;
+        *=)                                     ___x_cmd_var "$subcmd" "$@" ;;
+        i|install)                              xrc install/v0 && ___x_cmd_install "$@" ;;
 
-        initrc)                                 ( xrc x-cmd/_v0/initrc && ___x_cmd_initrc "$@"; ) ;;
+        login)                                  ( xrc hub/v0 && ___x_cmd_hub login "$@" ) ;;
+        register)                               ( xrc hub/v0 && ___x_cmd_hub register "$@" ) ;;
+        token)                                  ( xrc hub/v0 && ___x_cmd_hub token "$@" ) ;;
+        hub)                                    ( xrc hub/v0 && ___x_cmd_hub "$@" ) ;;
+
         log)                                    ( xrc x-cmd/_v0/log && ___x_cmd_log "$@"; ) ;;
 
-        rc|src)                                 xrc "$@" ;; # SRC_LOADER=bash eval "$(_xrc_print_code "$@")" ;;
-        *=)                                     ___x_cmd_var "$subcmd" "$@" ;;
-
-        i|install)                                ___x_cmd_install "$@" ;;
-
-        upgrade)    shift;  eval "$(curl https://get.x-cmd.com/script)" ;;
-        clear)      shift;
-                    if ! grep "___x_cmd_http_get()" "$___X_CMD_XRC_PATH/../boot" >/dev/null 2>&1; then
-                        xrc_log debug "'$___X_CMD_XRC_PATH/../boot' NOT found. Please manually clear cache folder: $___X_CMD_XRC_PATH"
+        upgrade)    eval "$(curl https://get.x-cmd.com/script)" ;;
+        clear)      if ! grep "___x_cmd_http_get()" "$___X_CMD_ROOT/xrc/v0" >/dev/null 2>&1; then
+                        xrc_log debug "'$___X_CMD_ROOT/xrc/v0' NOT found. Please manually clear cache folder: $___X_CMD_ROOT"
                         return 1
                     fi
-                    rm -rf "$___X_CMD_XRC_PATH" ;;
-        reinstall)
-                    xrc clear
-                    RELOAD=1 xrc upgrade
-                    ;;
+                    rm -rf "$___X_CMD_ROOT" ;;
+        reinstall)  xrc clear && RELOAD=1 xrc upgrade ;;
 
         z)                                      (   xrc zuz && zuz z "$@"   ) ;;
         uz)                                     (   xrc zuz && zuz uz "$@"  ) ;;
-        notify)                                 ___x_cmd_notify "$@"  ;;
 
         ubu|alp|deb|cen|bus)                    (   xrc xdk && xdk "$subcmd" "$@" ) ;;
         docker|dk|xdk)                          (   xrc xdk && xdk "$@" )   ;;
@@ -493,21 +372,20 @@ ___x_cmd_main(){
         javascript|js|node)                     ___x_cmd_node "$@" ;;
         npm)                                    ___x_cmd_npm "$@" ;;
         npx)                                    ___x_cmd_npx "$@" ;;
-        ts)
-            local arg
-            local argstr
-            while [ $# -ge 0 ]; do
-                case "$arg" in
-                    -*)     argstr="$argstr $arg"   ;;
-                    *)      break
-                esac
-            done
-            local script
-            # script="$(___x_cmd_official_which "$1")"
-            script="$1"
-            shift
-            x npx @typeshell/exec "$argstr" "$script" "$@"
-            ;;
+        ts)         local arg
+                    local argstr
+                    while [ $# -ge 0 ]; do
+                        case "$arg" in
+                            -*)     argstr="$argstr $arg"   ;;
+                            *)      break
+                        esac
+                    done
+                    local script
+                    # script="$(___x_cmd_official_which "$1")"
+                    script="$1"
+                    shift
+                    x npx @typeshell/exec "$argstr" "$script" "$@"
+                    ;;
         ruby|rb)                                ruby "$(___x_cmd_official_which "$2")" "$@"      ;;
         lua)            ;;
 
@@ -523,46 +401,31 @@ ___x_cmd_main(){
 
         run)                                    ___x_cmd_run_by_file "$@"            ;;
         search_path)                            ___x_cmd_search_path "$@"            ;;
-        which|w)
-            local p
-            for p in "$@"; do
-                if ! p=$(___x_cmd_which_one "$p"); then
-                    printf "%s\n" "Fail to find path for $p" >&2
-                    return
-                else
-                    printf "%s\n" "$p"
-                fi
-            done
-            ;;
-        _x_cmd_advise_json)     ___x_cmd_x_cmd_advise_json "$@" ;;
-        *)
-            local p
-            if p="$(___x_cmd_which_one "$subcmd" 2>/dev/null)"; then
-                ___x_cmd_run_by_file "$p" "$@" 2>/dev/null
-                return
-            fi
-
-            printf "%s" "$p"
+        which|w)    local p
+                    for p in "$@"; do
+                        if ! p=$(___x_cmd_which_one "$p"); then
+                            printf "%s\n" "Fail to find path for $p" >&2
+                            return
+                        else
+                            printf "%s\n" "$p"
+                        fi
+                    done
+                    ;;
+        _x_cmd_advise_json)                     ___x_cmd_x_cmd_advise_json "$@" ;;
+        *)          local p
+                    if p="$(___x_cmd_which_one "$subcmd" 2>/dev/null)"; then
+                        ___x_cmd_run_by_file "$p" "$@" 2>/dev/null
+                        return
+                    fi
+                    printf "%s" "$p"
     esac
 }
 
 # EndSection
 
-
 ___x_cmd_x_cmd_advise_json(){
     cat <<A
 {
-    "hub": {
-        "upload": {
-            "#1": "___advise_ls",
-            "#2": [ "@me/" ]
-        },
-        "share": [ "@me/" ],
-        "public": [ "@me/" ],
-        "private": [ "@me/" ],
-        "ls": [ "@me/" ]
-    },
-
     "update|u": {},
     "upgrade": {},
     "reinstall": {},
@@ -622,6 +485,4 @@ if [ -z "$XRC_NO_ADVISE" ] && [ -n "${BASH_VERSION}${ZSH_VERSION}" ] && [ "${-#*
     xrc advise/v0
     advise x
 fi
-
-
 
