Squashed 'mod/static-build/' changes from b51aeb16..c4e676cc
c4e676cc Merge branch 'master' of gitee.com:x-bash/static-build
b825f120 ...

git-subtree-dir: mod/static-build
git-subtree-split: c4e676cca31f8a8560cf91355abe7968a066ccb1

diff --git a/v0 b/v0
--- a/v0
+++ b/v0
@@ -30,8 +30,15 @@ static_build_which(){
     if [ ! -f "$target/$exe" ]; then
 
         static_build_log info "Downloading: ${repo}/bin/$exe.7z"
-        if ! CACHE="$target/$exe.7z" ___xcmd_curl_gitx static-build "${repo}/bin/$exe.7z"; then
-            static_build_log info "File Not Found. Perhaps the platform is NOT supported: $exe"
+
+        local url="https://gitee.com/static-build/${repo}/raw/master/bin/$exe.7z"
+        if [ "$___X_CMD_IN_CHINA_NET" != 1 ]; then
+            url="https://raw.githubusercontent.com/static-build/${repo}/master/bin/$exe.7z"
+        fi
+
+        if ! CACHE="$target/$exe.7z" ___x_cmd_curl "$url"; then
+            static_build_log warn "Download failure: $url"
+            static_build_log warn "File Not Found. Perhaps the platform is NOT supported: $exe"
             return 1
         fi
 
@@ -55,8 +62,8 @@ static_build_which(){
                     for i in $(seq "$size"); do
                         # suffix="$(printf "%03s" "$i")" # Not work in gnu bash
                         suffix="$(printf "%3s" "$i" | tr " " 0)"
-                        CACHE="$exe.7z.$suffix" ___xcmd_curl_gitx static-build "${repo}/bin/$exe.7z.$suffix" || {
-                            static_build_log info "Download failure in $exe.7z.$suffix" >&2
+                        CACHE="$exe.7z.$suffix" ___x_cmd_curl "$url.$suffix" || {
+                            static_build_log warn "Download failure in $exe.7z.$suffix" >&2
                             return 1
                         }
                     done
