Squashed 'mod/env/' changes from 6429ef13..3f7bb490
3f7bb490 !23 default value design && update lsenv && fix some bug Merge pull request !23 from padpar/issue_I5320J_review_20220424_lth
23ffd38b fix(all): lsenv gen use x-cmd/env
fd83445a fix(all): add pattern to ls_remote
07a79d26 refactor(common): remove some lsenv code
38c30964 fix(lsenv): list all candidate
57313f3f refactor(all): remove some unuse code
550dc346 fix(scala): remove scala special current
a4d2c717 feat(main): support 'x env download' to start lsenv
5b23c7fa feat(common): if no candidate for 'x env current' then print all candidate verison
f191b343 feat(common): if no candidate for 'x env current' then print all candidate verison
2b6e656e refactor(all): full_version => full_version_remote
b85748e3 feat(common): remove the shift
6c8f84dc feat(common): uninstall default to uninstall current version
b54d445f refactor(deno): update cache_expiration
ade6150a fix(common): local download_url
59e89a7a fix(common): remove #
ab293d1f refactor(deno): update ___X_CMD_ENV_PLATFORM
12179e26 test(candidate): split the testcase for candidate and common
06b4935d refactor(scala): update the version case
f4291d43 fix(scala): update scala case
2a7e3e7a fix(common): sort version use no -r
5d069c16 !22 add grep and sort functions Merge pull request !22 from mnnna/issue_I52MHC_sort_zyh
6545ffc4 fix env
66eff8b5 fix sort and grep
1f6a6e00 add version sort and grep
b9a1359e ls -r  add grep
ff44cba2 fix: update testcase
d8496147 refactor(log): env_log -> env:xxx && merge code
86cbaf40 !21 deno 和 testcase Merge pull request !21 from issue_I50Z1H_testcase_zyh
a6943860 deno
92d13b6c feat(main): support 'x env exec python[=<version-name>] [...python args]'
190cef38 deno
e26902b6 ..
1552fdf1 fix
35d32f82 ...
ee3f562c httpget replace
4bc78df4 refactor(current): remove gen from ls -r
d285158c deno
52c42ea2 refactor(current): candidate -> cmd
aefce775 feat(sdk): add TODO
10c0ff43 fix(current): current for maven and springboot
36f75478 refactor(latest): before review
44d3823b testcase
0f90d1c6 !19 新增perl Merge pull request !19 from mnnna/issue_I4D6KX_perl_zyh
efab1326 windows
d573a103 windows
3cd4a515 fix
85f09297 fix
79e545e5 new candidate perl
2d483595 new candidate perl
a20a2a7c feat(exec,which): Support for npm and a range of commands for npm downloads
b49dc44a new candidate : perl
cd468528 !17 go ，maven ，java兼容树莓派 Merge pull request !17 from mnnna/sbt_zyh
ad3eb3bb refactor: remove echo
23410d89 refactor(go): change platform arch var name
ae584fbb fix python ls -r function
55ebd8f2 fix go ls -r function
81021ee3 ...
814fc1f8 ...
fee74f8b refactor(go): add review todo
f9469995 Merge branch 'main' of gitee.com:x-bash/env update
a6f1b625 refactor(latest): update judgment logic for add path
34f2227e fix
f13d2696 go and java can use on pi
ecac4811 msome candidate can use on berrypi
4cb863b5 msome candidate can use on berrypi
89cc0852 merge(go): add more log
60bfa66c merge(go): add more log
33fb28e8 Merge remote-tracking branch 'origin/main' into sbt_zyh update
d64a1c8b add more testcases
8a1cf3a0 merge
cde1e989 fun,sbt

git-subtree-dir: mod/env
git-subtree-split: 3f7bb490f78dcb1f47dde074828139d7f54715f9

diff --git a/lib/app/lsenv b/lib/app/lsenv
--- a/lib/app/lsenv
+++ b/lib/app/lsenv
@@ -4,7 +4,23 @@ xrc ui/lib/region
 xrc ui/lib/varctl
 
 ___x_cmd_ui_lsenv(){
+    local tgzfilepath="$___X_CMD_ENV_PATH/info.tgz"
+    if ! ___x_cmd_httpget_gitx x-cmd env main "dist/info.tgz" "$tgzfilepath" 86400; then # 1-day
+        env:error "Unaviable info.tgz. Unable to fetch info.tgz."
+        return 1
+    fi
+    x uz "$tgzfilepath" "$___X_CMD_ENV_PATH" 2>/dev/null
+
+    local ___X_CMD_UI_LSENV_FINAL_COMMAND
+    local ___X_CMD_UI_LSENV_CURRENT_VERSION
     ___x_cmd_ui_region_autorefresh_with_keyboard ___x_cmd_ui_lsenv_mainloop_awk
+    if ! [ "$___X_CMD_UI_LSENV_FINAL_COMMAND" = "ENTER" ] \
+        || [ -z "$___X_CMD_UI_LSENV_CURRENT_CANDIDATE" ] \
+        || [ -z "$___X_CMD_UI_LSENV_CURRENT_VERSION" ] ; then
+        return 1
+    fi
+    candidate="$___X_CMD_UI_LSENV_CURRENT_CANDIDATE"
+    version="$___X_CMD_UI_LSENV_CURRENT_VERSION"
 }
 
 ___x_cmd_ui_lsenv_mainloop_awk_(){
@@ -29,16 +45,15 @@ ___x_cmd_ui_lsenv_mainloop_awk(){
     fi
 }
 
-
-CODE="$(xrc cat awk/lib/default.awk awk/lib/json.awk awk/lib/jiter.awk )"
-
 ___x_cmd_ui_get_env_ls(){
     local kp="${1:-"."}"
-    cat | awk -v keypath="$kp" "$CODE"'
+    local code
+    code="$(xrc cat awk/lib/default.awk awk/lib/json.awk awk/lib/jiter.awk )"
+    cat | awk -v keypath="$kp" "$code"'
 {
     jiter_print_eqarr_after_tokenize($0, keypath, "\n", "\n")
 }
-' | awk "$CODE"'
+' | awk "$code"'
 function print_env_ls(item){
     if ($0 == "") return
     if ( PRINT_ENV_LS == 0 ) {
diff --git a/lib/candidate/python b/lib/candidate/python
--- a/lib/candidate/python
+++ b/lib/candidate/python
@@ -2,63 +2,71 @@
 
 # Section: utils
 
-___x_cmd_env_python_get_system_platform(){
-    xrc os
-    case "$(___x_cmd_os name)" in
-        linux)      system=Linux            ;;
-        windows)    system=Windows          ;;
-        darwin)     system=MacOSX           ;;
-        *)          return 1 ;;
+___x_cmd_env_python_get_platform_arch(){
+
+    local _platform
+    local _arch
+    _platform="$(x os name)"
+    _arch="$(x os arch)"
+
+    case "$_platform" in
+        linux)      ___X_CMD_ENV_PLATFORM=Linux                     ;;
+        windows)    ___X_CMD_ENV_PLATFORM=Windows                   ;;
+        darwin)     ___X_CMD_ENV_PLATFORM=MacOSX                    ;;
+        *)          env:error "your arch:(" "$_platform" ") are not supported"
+                    return 1
+                    ;;
     esac
 
-    case "$(___x_cmd_os arch)" in
-        aarch64)    platform=aarch64        ;;
-        x64)        platform=x86_64         ;;
-        arm64)      platform=arm64          ;;
-        *)          return 1 ;;
+    case "$_arch" in
+        aarch64|arm64|armv7l|armv6l)    ___X_CMD_ENV_ARCH="$_arch"   ;;
+        x64)                            ___X_CMD_ENV_ARCH=x86_64     ;;
+        *)          env:error "your arch:(" "$_arch" ") are not supported"
+                    return 1
+                    ;;
     esac
 }
 
 ___x_cmd_env_python_get_miniconda_filename_and_compression(){
     local version="${1:?Provide python version}"
 
-    local platform
-    local system
-    ___x_cmd_env_python_get_system_platform
-
-    if [ $system = "Windows" ] ; then
-        compression="exe"
-    else
-        compression="sh"
+    local ___X_CMD_ENV_PLATFORM
+    local ___X_CMD_ENV_ARCH
+    if ___x_cmd_env_python_get_platform_arch ; then
+        if [ $___X_CMD_ENV_PLATFORM = "Windows" ] ; then
+            ___X_CMD_ENV_COMPRESSION="exe"
+        else
+            ___X_CMD_ENV_COMPRESSION="sh"
+        fi
     fi
-    miniconda_filename="Miniconda3-${version}-${system}-${platform}.${compression}"
+    miniconda_filename="Miniconda3-${version}-${___X_CMD_ENV_PLATFORM}-${___X_CMD_ENV_ARCH}.${___X_CMD_ENV_COMPRESSION}"
 }
 
 # EndSection
 
 # Section: ls, la
 
-___x_cmd_env_python_sort_versions(){
-	sort -t . -k 1,1 -k 2,2n
-}
-
 ___x_cmd_env_python_ls_remote(){
-    # local pattern="${1:-""}"    # TODO: ls remote filter
-    local cache_expiration="${2:-1}"
+    local pattern="${1:-""}"
+    local cache_expiration="${2:-86400}"
 	local cache_path="$___X_CMD_ENV_PATH/python/cache/version_list"
 
-    local platform
-    local system
-    ___x_cmd_env_python_get_system_platform
+    local ___X_CMD_ENV_PLATFORM
+    local ___X_CMD_ENV_ARCH
 
-    ___x_cmd_httpget "https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/" "$cache_path" "$cache_expiration" && \
-    awk -v platform="${platform}" -v arch="${system}" '
-        BEGIN{RS="<a href=";FS="\""}{
-            if (match($2, "^.*-" arch "-" platform ".sh$")) {
-                split($2, a, /-/)
-                print a[2]
-            }
-        }' <"$cache_path" | ___x_cmd_env_python_sort_versions | uniq
+    if ___x_cmd_env_python_get_platform_arch ; then
+        ___x_cmd_httpget "https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/" "$cache_path" "$cache_expiration" && \
+        awk -v pattern="$pattern" -v platform="${___X_CMD_ENV_PLATFORM}" -v arch="$___X_CMD_ENV_ARCH" '
+            BEGIN{RS="<a href=";FS="\""}{
+                if (match($2, "^.*-" platform "-" arch ".sh$")) {
+                    split($2, a, /-/)
+                    version = a[2]
+                    if (pattern == "" || index(version, pattern) > 0) {
+                        print version
+                    }
+                }
+            }' <"$cache_path" | ___x_cmd_env_common_sort_version | ___x_cmd_env_common_simplify_version
+    fi
 }
 
 # EndSection
@@ -69,44 +77,46 @@ ___x_cmd_env_python_download_archive(){
     local version="${1:?Provide python version}"
 
     if ___x_cmd_env_util_is_archive_cached python "$version" 2>/dev/null; then
-        env_log info "Archive existed: $version"
+        env:info "Archive existed: $version"
         return 0
     fi
 
     local miniconda_filename
-    local compression
+    local ___X_CMD_ENV_COMPRESSION
     ___x_cmd_env_python_get_miniconda_filename_and_compression "$version"
 
-    local archive_path="$___X_CMD_ENV_PATH/python/archive/python-$version.$compression"
+    local archive_path="$___X_CMD_ENV_PATH/python/archive/python-$version.$___X_CMD_ENV_COMPRESSION"
     mkdir -p "$(dirname "$archive_path")"
+
+    # TODO: use function to switch mirror
     local url="https://repo.anaconda.com/miniconda"
     if [ "${___X_CMD_IN_CHINA_NET:-0}" -eq 1 ]; then
         url="https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda"
     fi
 
-    env_log info "Downloading $url/$miniconda_filename"
-    if curl --fail --output "$archive_path" "$url/$miniconda_filename"; then
-        env_log info "Download completed python-$version.$compression"
-        return
-    else
-        env_log error "Download failure from $url/${miniconda_filename}"
+    local download_url="$url/$miniconda_filename"
+    env:info "Downloading $download_url"
+    if ! curl --fail --output "$archive_path" "$download_url"; then
+        env:error "Download failure from $download_url"
         return 1
     fi
+
+    env:info "Download completed $archive_path"
 }
 
 ___x_cmd_env_python_unpack(){
     local version="${1:?Provide python version}"
     local miniconda_filename
-    local compression
+    local ___X_CMD_ENV_COMPRESSION
     ___x_cmd_env_python_get_miniconda_filename_and_compression "$version"
 
-    env_log info "Unpacking python-$version.$compression"
+    env:info "Unpacking python-$version.$___X_CMD_ENV_COMPRESSION"
 
     local versions_path="$___X_CMD_ENV_PATH/python/versions"
     mkdir -p "${versions_path}"
-    local archive_path="$___X_CMD_ENV_PATH/python/archive/python-$version.$compression"
+    local archive_path="$___X_CMD_ENV_PATH/python/archive/python-$version.$___X_CMD_ENV_COMPRESSION"
     chmod +x "${archive_path}" && \
-    "${archive_path}" -b -u -p "${versions_path}/${version}" 1>&2
+        "${archive_path}" -b -u -p "${versions_path}/${version}" 1>&2
 }
 
 # EndSection
diff --git a/lib/common b/lib/common
--- a/lib/common
+++ b/lib/common
@@ -1,22 +1,49 @@
 # shellcheck shell=sh disable=SC2039,SC1090,SC3043,SC2263    # xrc
 
-# Section: full_version ls_local ls_remote
+# Section: full_version_remote sort_version simplify_version
 
-# TODO: Not proper implemented
-___x_cmd_env_common_full_version(){
+___x_cmd_env_common_full_version_remote(){
     local candidate="${1:?Provide candidate}"
-    local version="${2}"
-
-    if [ -z "$version" ]; then
-        ___x_cmd_env_"$candidate"_ls_remote "$version" "$3" | awk 'END{ if (NR<=0) { exit(1) } else print $1;}'
-    fi
-    printf "%s\n" "$version"
+    local pattern="${2}"
+    ___x_cmd_env_run_common_if_notfound ls_remote "$candidate" "$pattern" "$3" \
+        | awk 'END{ if (NR<=0) { exit(1) } else print $1;}'
 }
 
+___x_cmd_env_common_full_version_local(){
+    local candidate="${1:?Provide candidate}"
+    local pattern="${2}"
+    ___x_cmd_env_run_common_if_notfound ls_local "$candidate" "$pattern" "$3" \
+        | awk 'END{ if (NR<=0) { exit(1) } else print $1;}'
+}
+
+___x_cmd_env_common_sort_version(){
+    sort -V
+}
+
+___x_cmd_env_common_simplify_version(){
+    awk '{
+        version = $1
+        match(version, /[0-9]+\.[0-9+]+/)
+        prefix = substr(version,RSTART+0,RLENGTH-0)
+
+        if ( uniq_map[ prefix ] == "" && last != "" ) {
+            print last
+            uniq_map[ prefix ] = 1
+        }
+        last = version
+    }
+    END{ if ( last != "" ) { print last ; }}'
+}
+# EndSection
+
+# Section: ls_local
 ___x_cmd_env_common_ls_local(){
     local candidate="${1:?Provide candidate}"
+    local pattern="${2}"
     if [ -d "$___X_CMD_ENV_PATH/$candidate/versions" ]; then
-        ls "$___X_CMD_ENV_PATH/$candidate/versions"
+        for version in "$___X_CMD_ENV_PATH/$candidate/versions"/*"$pattern"* ; do
+            printf "%s\n" "${version##*/}"
+        done 2>/dev/null | ___x_cmd_env_common_sort_version
     fi
 }
 
@@ -70,9 +97,8 @@ ___x_cmd_env_common_use(){
     ___x_cmd_env_util_add_path "$version_path" || return 1
 
     ___x_cmd_env_common_init_file_add "$candidate" "$version_path" && \
-        # ___x_cmd_modfile_add "$___X_CMD_ROOT/.env/env/use" "$version_path" && \
             printf "%s\n" "$version" > "$___X_CMD_ENV_PATH/$candidate/version" && \
-                env_log info "Using $candidate $version -> $___X_CMD_ENV_PATH/$candidate/version"
+                env:info "Using $candidate $version -> $___X_CMD_ENV_PATH/$candidate/version"
 }
 
 ___x_cmd_env_common_try(){
@@ -82,7 +108,7 @@ ___x_cmd_env_common_try(){
 
     ___x_cmd_env_util_is_downloaded "$candidate" "$version" 2>/dev/null || return 1
     ___x_cmd_env_util_add_path "$version_path" && \
-        env_log info "Setting ${candidate} ${version} in current Shell."
+        env:info "Setting ${candidate} ${version} in current Shell."
 }
 
 # EndSection
@@ -90,20 +116,20 @@ ___x_cmd_env_common_try(){
 # Section: current
 
 ___x_cmd_env_common_current(){
-    local candidate="${1:?Provide candidate}"
-    local candidate_path
-    candidate_path="$(command -v "$candidate")"
+    local cmd="${1:?Provide command}"
+    local cmd_path
+    cmd_path="$(command -v "$cmd")"
 
-    # No any candidate version
-    if [ -z "$candidate_path" ]; then
-        env_log error "No version of $candidate detected, please install it first! "
+    # No any cmd version
+    if [ -z "$cmd_path" ]; then
+        env:error "No version of $cmd detected, please install it first! "
         return 1
 
-    # After try and no candidate version in xenv, but has candidate version in current shell.
-    elif [ "$candidate_path" != "$___X_CMD_ENV_PATH/$candidate/shims/$candidate" ]; then
-        local try_path="${candidate_path#*"versions/"}"
+    # After try and no cmd version in xenv, but has cmd version in current shell.
+    elif [ "$cmd_path" != "$___X_CMD_ENV_PATH/$cmd/shims/$cmd" ]; then
+        local try_path="${cmd_path#*"versions/"}"
         try_path="${try_path%%/*}"
-        if [ "$try_path" != "$candidate" ] && [ -n "$try_path" ]; then
+        if [ "$try_path" != "$cmd" ] && [ -n "$try_path" ]; then
             printf "%s\n" "$try_path"
         else
             printf "%s\n" "system"
@@ -113,14 +139,14 @@ ___x_cmd_env_common_current(){
     # Use(shims)
     else
         local version
-        if ! version=$(___x_cmd_env_util_shims_which_version "$candidate"); then
-            env_log error "No version of $candidate detected, please download it first! "
+        if ! version=$(___x_cmd_env_util_shims_which_version "$cmd"); then
+            env:error "No version of $cmd detected, please download it first! "
             return 1
         fi
 
-        local exactly_path="$___X_CMD_ENV_PATH/$candidate/versions/$version/bin/$candidate"
+        local exactly_path="$___X_CMD_ENV_PATH/$cmd/versions/$version/bin/$cmd"
         if [ ! -f "$exactly_path" ]; then
-            env_log error "No such file: $exactly_path"
+            env:error "No such file: $exactly_path"
             return 1
         fi
 
@@ -136,17 +162,17 @@ ___x_cmd_env_common_download(){
     local version="${2:?Provide version}"
 
     if ___x_cmd_env_util_is_downloaded "$candidate" "$version" 2>/dev/null ; then
-        env_log info "Already downloaded $candidate $version"
+        env:info "Already downloaded $candidate $version"
         return 0
     fi
 
     if ! ___x_cmd_env_run_common_if_notfound download_archive "$candidate" "$version"; then
-        env_log error "Failed to download $candidate $version"
+        env:error "Failed to download $candidate $version"
         return 1
     fi
 
     if ! ___x_cmd_env_run_common_if_notfound unpack "$candidate" "$version"; then
-		env_log error "Failed to unpack $candidate of version: $version."
+		env:error "Failed to unpack $candidate of version: $version."
 		return 1
 	fi
 }
@@ -159,20 +185,20 @@ ___x_cmd_env_common_install(){
     local version="${2:?Provide version}"
     local use_shims="${3:-""}"
 
-    env_log info "Installing $candidate $version"
+    env:info "Installing $candidate $version"
     if ! ___x_cmd_env_run_common_if_notfound download "$candidate" "$version"; then
-        env_log error "Failed to installed $candidate of version: $version."
+        env:error "Failed to installed $candidate of version: $version."
         return 1
     fi
 
     ___x_cmd_env_common_use "$candidate" "$version" "$use_shims" || return 1
-    env_log info "Successfully installed $candidate $version"
+    env:info "Successfully installed $candidate $version"
 }
 
 ___x_cmd_env_common_uninstall(){
     local candidate="${1:?Provide candidate}"
     local version="${2:?Provide the version}"
-    env_log info "Uninstalling $1 $2"
+    env:info "Uninstalling $1 $2"
 
     local candidate_path="$___X_CMD_ENV_PATH/${candidate}/versions/${version}"
     if [ -d "$candidate_path" ]; then
@@ -189,19 +215,21 @@ ___x_cmd_env_common_uninstall(){
 # Section: which, exec
 ___x_cmd_env_common_which(){
     local candidate="${1:?Provide candidate}"
-    local candidate_path
-    candidate_path="$(command -v "$candidate")"
+    local cmd="${2:-"$candidate"}"
+    local cmd_path
+    cmd_path="$(command -v "$cmd")"
 
-    if [ "$candidate_path" != "$___X_CMD_ENV_PATH/$candidate/shims/$candidate" ]; then
-        command -v "$candidate"
+    env:debug "cmd_path: $cmd_path, cmd: $cmd"
+    if [ "$cmd_path" != "$___X_CMD_ENV_PATH/$candidate/shims/$cmd" ]; then
+        command -v "$cmd"
         return 0
     fi
 
     local version
     if version=$(___x_cmd_env_util_shims_which_version "$candidate"); then
-        local exactly_path="$___X_CMD_ENV_PATH/$candidate/versions/$version/bin/$candidate"
+        local exactly_path="$___X_CMD_ENV_PATH/$candidate/versions/$version/bin/$cmd"
         if [ ! -f "$exactly_path" ]; then
-            env_log error "No such file: $exactly_path"
+            env:error "No such file: $exactly_path"
             return 1
         fi
         printf "%s\n" "$exactly_path"
@@ -210,39 +238,14 @@ ___x_cmd_env_common_which(){
 
 ___x_cmd_env_common_exec(){
     local candidate="${1:?Provide candidate}"
-    local version="${2:?Provide version}"; shift 2
-    ___x_cmd_env_util_is_downloaded "${candidate}" "${version}" 2>/dev/null || return 1
-    PATH="${___X_CMD_ENV_PATH}/${candidate}/versions/${version}/bin:$PATH" "${candidate}" "$@"
-}
-# EndSection
+    local cmd="${2:?Provide command}"
+    local version="${3:?Provide version}"; shift 3
 
-# Section: ui_catsel
-
-___x_cmd_env_common_rec(){
-    local cmd="$1"
-    local space="${2:-""}"
-    eval "$cmd" | while read -r line ; do
-        if [ -n "$line" ] ; then
-            CODE="${CODE}
-${space}  \"$line\":{"
-
-            ___x_cmd_env_common_rec "$cmd $line" "$space  "
-
-            CODE="${CODE%,}
-${space}  },"
-        fi
-    done
-}
-
-___x_cmd_env_common_gen(){
-    if [ -f "${___X_CMD_ENV_PATH}/${candidate}/cache/${candidate}.json" ]; then
-        return 0
+    if ! ___x_cmd_env_util_is_downloaded "${candidate}" "${version}" 2>/dev/null ; then
+        env:error "Candidate $candidate No such version: $version"
+        return 1
     fi
-    local CODE="{"
-    local candidate="$1"
-    cmd="x env ___x_cmd_ui_catsel $candidate"
-    ___x_cmd_env_common_rec "$cmd"
-    printf "%s" "${CODE%,}
-}" > "${___X_CMD_ENV_PATH}/${candidate}/cache/${candidate}.json"
+    env:info "Executing $candidate $version $cmd"
+    PATH="${___X_CMD_ENV_PATH}/${candidate}/versions/${version}/bin:$PATH" "$cmd" "$@"
 }
 # EndSection
