Squashed 'mod/dev/' changes from cb60749e..d116db0a
d116db0a ...
c3648b6b ...
a76ea081 ...
ccb8222e ...
8283a9a5 ...
4edfedf3 ...
66b1f1d5 ...
3100f6f5 ...
d782d441 ...
78c6ce05 ...
2f128fdd ...
d4182fc8 ...
b1c37610 ...
d7fcc4e3 ...

git-subtree-dir: mod/dev
git-subtree-split: d116db0a53dd28b8d0797ee66bc0afdbbd9afde4

diff --git a/lib/all b/lib/all
--- a/lib/all
+++ b/lib/all
@@ -8,10 +8,13 @@
 ___x_cmd_dev_all(){
     param:dsl <<A
 subcommand:
+    init        "init"
     pull        "pull"
     push        "push"
-    update      "update"
+    repolist    "Show all repo"
+    repo        "clone or update all repos"
     clone       "clone"
+    map         "map"
     ls          "list modules"
 A
     param:run
@@ -24,22 +27,57 @@ A
     "___x_cmd_dev_all_${PARAM_SUBCMD}" "$@"
 }
 
-___x_cmd_dev_all_clone(){
-    local n
-    ___x_cmd_dev_all_ls | while read -r n; do
-        git clone "git@gitee.com:x-bash/$n.git"
-    done
+
+___x_cmd_dev_all_repolist(){
+    # ___x_cmd_curl_gitx x-cmd x-cmd main repolist
+    curl https://gitee.com/x-cmd/x-cmd/raw/main/repolist 2>/dev/null | awk '{ if ($0 ~ /^\+/) gsub(/^\+/, "", $0); print $0 }'
 }
 
-___x_cmd_dev_all_update(){
-    local n
-    ___x_cmd_dev_all_ls | while read -r n; do
-        if [ -d "$n" ]; then
-            ( cd $n && git pull origin main && cd - )
+___x_cmd_dev_all_map(){
+    local curdir="${1:-$HOME}"
+    local x_bash_eval="${2:?Provide sentence}"
+    local x_cmd_eval="${3:-"$2"}"
+
+    [ ! -d "$curdir" ] && printf "Exepct a directory: %s\n" "$curdir" >&2 && return 1
+
+    { mkdir -p "$curdir/x-bash" && cd "$curdir/x-bash" && cd -; } || printf "Cannot not enter directory: %s\n" "$curdir"
+    { mkdir -p "$curdir/x-cmd" && cd "$curdir/x-cmd" && cd -; } || printf "Cannot not enter directory: %s\n" "$curdir"
+
+
+    (
+        cd "$curdir/x-bash" && {
+            local org=x-bash
+            local name
+            ___x_cmd_dev_all_ls | while read -r name; do
+                ( eval "$x_bash_eval"; )
+            done
+        }
+    ) && (
+        cd "$curdir/x-cmd" && {
+            local name
+            local org=x-cmd
+            ___x_cmd_dev_all_repolist | while read -r name; do
+                ( eval "$x_cmd_eval"; )
+            done
+        }
+    )
+}
+
+# shellcheck disable=SC2016
+___x_cmd_dev_all_clone(){
+    ___x_cmd_dev_all_map "${1:-$HOME}" \
+        'git clone "git@gitee.com:$org/$name.git"'
+}
+
+# shellcheck disable=SC2016
+___x_cmd_dev_all_repo(){
+    ___x_cmd_dev_all_map "${1:-$HOME}" '
+        if [ -d "$name" ]; then
+            cd "$name" && git pull && git pull origin main
         else
-            git clone "git@gitee.com:x-bash/$n.git"
+            git clone "git@gitee.com:$org/$name.git"
         fi
-    done
+    '
 }
 
 ___x_cmd_dev_all_ls(){
