Squashed 'mod/xrc/' changes from c24ed11..5ae5887
5ae5887 fix(latest): xrc advise
e7bce87 ...
05eedd9 ...
01f260c ...
0e9cfa5 ...
7b4aba3 ...
cd8e1e2 ...
97987a5 ...
98313df ...
a7d912a ...
b55794a ...
9cc4a6c ...
f181a14 ...
9088f57 ...
e32faa4 ...
18c7e32 ...
a82dcca ...
7f67653 ...
aa58325 ...
9556358 ...
8a22981 ...
3d6f8f8 ...
2893328 ...
04cac73 ...
e56fa85 ...
e90042a ...
9430c95 ...
e11e3bf ...
440533f ...
49a100d ...
a9d27e5 ...
8b75430 ...
d08ebdb ...
184fd0e ...
31217d7 ...
ca0e456 ...
54f5f2e ...
7c11575 ...
3626004 ...
6bcfe9f ...
b06c2a2 ...
302b1e1 ...
c2a88b4 fix xrc:mod
288e291 fix ___X_CMD_ROOT_MOD is null

git-subtree-dir: mod/xrc
git-subtree-split: 5ae5887acec04f98fba59af4ee87cd59b53ebd4f

diff --git a/lib/request_curl b/lib/request_curl
--- a/lib/request_curl
+++ b/lib/request_curl
@@ -3,11 +3,11 @@
 # author:       Li Junhao           l@x-cmd.com
 # maintainer:   Li Junhao
 # license:      GPLv3
-___x_cmd_http_not_secure_request_nc(){
+___x_cmd_http___not_secure_request_nc(){
     printf "GET %s HTTP/1.1\r\nHost: %s\r\nUser-Agent: curl/7.64.1\r\nAccept: */*\r\nConnection: close\r\n\r\n" "$path" "$host" | nc "$host" 80
 }
 
-___x_cmd_http_not_secure_request_bash()(
+___x_cmd_http___not_secure_request_bash()(
     host="$host" path="$path" bash -c '
         exec 88<>"/dev/tcp/$host/80"
         printf "GET %s HTTP/1.1\r\nHost: %s\r\nUser-Agent: curl/7.64.1\r\nAccept: */*\r\nConnection: close\r\n\r\n" "$path" "$host" >&88
@@ -19,7 +19,7 @@ ___x_cmd_http_not_secure_request_bash()(
 
 ___X_CMD_HTTP_NOT_SECURE_REQUEST_HANDLER_R="$(printf "\r")"
 
-___x_cmd_http_not_secure_request_handler(){
+___x_cmd_http___not_secure_request_handler(){
     local file="${1:?Provide cache filepath}"
     local line
     while read -r line; do
@@ -33,8 +33,8 @@ ___x_cmd_http_not_secure_request_handler(){
     cat >"$file"
 }
 
-# Test: ___x_cmd_http_not_secure_get gitee.com/ a.txt
-___x_cmd_http_not_secure_get(){
+# Test: ___x_cmd_http___not_secure_get gitee.com/ a.txt
+___x_cmd_http___not_secure_get(){
     local path="${1:?Provide path}"
     local file="${2:?Provide cache file}"
 
@@ -49,7 +49,7 @@ ___x_cmd_http_not_secure_get(){
 
     if command -v bash 1>/dev/null; then
         ___x_cmd_http_not_secure_request(){
-            ___x_cmd_http_not_secure_request_bash
+            ___x_cmd_http___not_secure_request_bash
         }
     elif command -v wget >/dev/null; then
         ___x_cmd_http_not_secure_request(){
@@ -57,7 +57,7 @@ ___x_cmd_http_not_secure_get(){
         }
     elif command -v nc 1>/dev/null; then
         ___x_cmd_http_not_secure_request(){
-           ___x_cmd_http_not_secure_request_nc
+           ___x_cmd_http___not_secure_request_nc
         }
     else
         printf "Not support without wget, bash or nc." >&2
@@ -65,10 +65,10 @@ ___x_cmd_http_not_secure_get(){
     fi
 
     local code=0
-    ___x_cmd_http_not_secure_request | ___x_cmd_http_not_secure_request_handler "$file"| ___x_cmd_httpget_handle_resp_header "$file" "$code"
+    ___x_cmd_http_not_secure_request | ___x_cmd_http___not_secure_request_handler "$file"| ___x_cmd_httpget_handle_resp_header "$file" "$code"
 }
 
-___x_cmd_http_download_curl(){
+___x_cmd_http___download_curl(){
     xrc os
     local arch
     arch="$(os arch)"
@@ -86,11 +86,11 @@ ___x_cmd_http_download_curl(){
     esac
     if [ ! -e "$target/$app" ];then
         mkdir -p "$target"
-        ___x_cmd_http_not_secure_get "http://$url/$app.tar.gz" "$target/$app.tar.gz" 2>/dev/stdout || return 1
+        ___x_cmd_http___not_secure_get "http://$url/$app.tar.gz" "$target/$app.tar.gz" 2>/dev/stdout || return 1
         local tarsha
         tarsha="$(sha256sum "$target"/"$app".tar.gz)"
         [ "$sha" = "${tarsha%% *}" ] && tar zxvf "$target/$app.tar.gz" -C "$target" && return 0
-        ___xrc_log error "$app sha256 match fail"
+        x:error "$app sha256 match fail"
         return 1
     fi
     return 0
