Squashed 'mod/env/' changes from f4cbe69e..6429ef13
6429ef13 ...
bad62422 refactor(main): change env log
cacee118 refactor(main): format code
55832564 fix
8e2571e4 refactor(main): refactor some code
eef2efc4 refactor(main): refactor some code
6aaa5cc6 !16 add scala，kotlin，maven，springboot，go，ruby Merge pull request !16 from issue_I4XW5Y_gradle_lth
288d8959 refactor(main): remove candidate deno and ruby
c1876492 feat(env): add testcase
842d0535 feat(env): add cross test
1ceabe28 fix exec function of scala and kotlin
30014f9d fix exec function of scala and kotlin
fe47c663 feat(env): add testcases
914791d0 Merge branch 'main' of https://gitee.com/x-bash/env into main
fd43ecea feat(env): update use ___X_CMD_ROOT_MOD and TH_THEME_COLOR
4d98b4b9 feat(env): add all lsenv
11b973ea fix section
ee5dd3fe fix functions and format of candidates
9d111a9f update
fb45aacb style(env): update
b5b361af refactor(env): modify some designs
b3d0881e refactor(env): modify some designs
051193cb Merge branch 'issue_I4XW5Y_gradle_lth' of https://gitee.com/x-bash/env into issue_I4XW5Y_gradle_lth
fecf9e0b fix go install
aabdc8fb refactor(node): remove comment
315c817f refactor(node): remove all
00679d3a refactor(node): archive_url -> download_url
7a60f01c refactor(latest): If the folder does not exist, then create
0e3535d0 Merge remote-tracking branch 'origin/main' into issue_I4XW5Y_gradle_lth update
735d04e0 merge: merge main branch
3d2209cf merge: merge main branch
5ccc0ad6 fix go
3f19da1e fix go , maven ,ruby ,scala ,springboot ls -r function
b050ce91 fix(env): remove duplicates from python ls remote
481fb765 fix
4fa225e9 fix(env): fix the problem of path overlapping
a624bedd fix scala
0c4751aa fix scala unpack function
b7500cd1 fix scala unpack function
378512fc refactor(main): remove -___x_cmd_env_candidate_has
64a5e34c fix scala download_archive
b9f886bc go
9bb1b74a add ruby
8c3046e6 fix go
119b8ace add ruby
547c97c6 fix go
1d15f468 fix : go
dd908445 go
9483d5f2 new language:golang

git-subtree-dir: mod/env
git-subtree-split: 6429ef13e6752ede02a2270719a6b92331f7b69a

diff --git a/lib/candidate/node b/lib/candidate/node
--- a/lib/candidate/node
+++ b/lib/candidate/node
@@ -5,7 +5,7 @@ ___X_CMD_ENV_NODE_MIRROR="https://nodejs.org/dist"
 # Section: full_version, ls_local, ls_remote
 
 ___x_cmd_env_node_full_version(){
-    ___x_cmd_env_node_ls_remote "${1:?Provide node version pattern}" "$2" | awk 'END{ if (NR<=0) { exit(1) } else print $1;}'
+    ___x_cmd_env_node_ls_remote "$1" "$2" | awk 'END{ if (NR<=0) { exit(1) } else print $1;}'
 }
 
 ___x_cmd_env_node_sort_versions(){
@@ -17,12 +17,12 @@ ___x_cmd_env_node_ls_remote(){
     local cache_expiration="${2:-1}"
     local cache_path="$___X_CMD_ENV_PATH/node/cache/version_list"
 
-	___x_cmd_httpget "$___X_CMD_ENV_NODE_MIRROR/index.tab" "$cache_path" "$cache_expiration" 2>/dev/null && \
+	___x_cmd_httpget "$___X_CMD_ENV_NODE_MIRROR/index.tab" "$cache_path" "$cache_expiration" && \
     awk -v pattern="$pattern" -v prev_codename="x-cmd" '
         ((NR>1)&&($1)){
             codename=$10
             version=$1
-            if ( (pattern != "") || ( index( version, pattern ) > 0 ) ) {
+            if ( (pattern == "") || ( index( version, pattern ) > 0 ) ) {
                 if (codename ~ /^\-?$/)                                 print version
                 else if (codename!="" && codename != prev_codename)     print version, codename, "*"        # The latest version of this code name
                 else                                                    print version, codename
@@ -67,16 +67,16 @@ A
 
     # TODO: node <= 0.1.13 does not have a directory
     local slug="node-${version}-${platform}-${arch}"
-    local archive_url="${___X_CMD_ENV_NODE_MIRROR}/${version}/${slug}.${compression}"
-    if ! curl -L -C - --progress-bar "${archive_url}" -o "${archive_path}"; then
+    local download_url="${___X_CMD_ENV_NODE_MIRROR}/${version}/${slug}.${compression}"
+    if ! curl -L -C - --progress-bar "${download_url}" -o "${archive_path}"; then
         rm -rf "${archive_path}"
-        env_log error "Download from ${archive_url} failed."
+        env_log error "Download from ${download_url} failed."
         return 1
     fi
 
     # TODO: checksum
 
-    env_log info "Downloaded ${archive_url} to ${archive_path}"
+    env_log info "Downloaded ${download_url} to ${archive_path}"
 }
 # EndSection
 
@@ -133,17 +133,9 @@ A
 #TODO: Should be optimized
 ___x_cmd_env_node_ui_catsel(){
     case "$#" in
-        0)
-            ___x_cmd_env_node_ls_remote \
-                | awk '{ split($0,arr," "); if(arr[2]!=""){ vmap[arr[2]]=1 }else if(arr[2]==""){ split(arr[1],varr,"."); vmap[varr[1]]=1 } } END{ for(key in vmap){ print key } }'
-            ;;
-        1)
-            ___x_cmd_env_node_ls_remote | grep "$1" | awk '{ split($0,arr,"."); vmap[arr[1]]=1 } END{ for(key in vmap){print key} }'
-            ;;
-        2)
-            ___x_cmd_env_node_ls_remote | grep "$1" | grep "$2" \
-            | awk -v a="$1" -v b="$2" '{ if( a != b){ print $1 }else{ split($0,arr," "); if(arr[2]==""){ vmap[arr[1]]=1 } } } END{ for(key in vmap){ print key } }'
-            ;;
+        0)  ___x_cmd_env_node_ls_remote | awk '{ split($0,arr," "); if(arr[2]!=""){ vmap[arr[2]]=1 }else if(arr[2]==""){ split(arr[1],varr,"."); vmap[varr[1]]=1 } } END{ for(key in vmap){ print key } }' ;;
+        1)  ___x_cmd_env_node_ls_remote | grep "$1" | awk '{ split($0,arr,"."); vmap[arr[1]]=1 } END{ for(key in vmap){print key} }' ;;
+        2)  ___x_cmd_env_node_ls_remote | grep "$1" | grep "$2" | awk -v a="$1" -v b="$2" '{ if( a != b){ print $1 }else{ split($0,arr," "); if(arr[2]==""){ vmap[arr[1]]=1 } } } END{ for(key in vmap){ print key } }' ;;
     esac
 }
 
