...

diff --git a/.x-cmd/lsmod b/.x-cmd/lsmod
--- a/.x-cmd/lsmod
+++ b/.x-cmd/lsmod
@@ -1,90 +1,34 @@
 #! /usr/bin/env xsh
 
-core_mod_list="
-xrc
-x-cmd
-hub
-install
-awk
-x_fs
 
-# basic modules: non dependency
-str
-list
-dict
-assert
-json
-os
-cowsay
+lsmod_getfp(){
+    local filename=modlist
+    local fp="$(pwd)/$filename"
+    [ -f "$fp" ] && printf "%s" "$fp" && return
 
-# basic modules: dependencies
-param
-http
-advise
-ui
+    fp="$(x wsroot)/$filename"
+    [ -f "$fp" ] && printf "%s" "$fp" && return
 
-# modules
-static-build
-ccmd
-"
-
-
-mod_list="
-xrc
-x-cmd
-hub
-install
-awk
-x_fs
-
-# basic modules: non dependency
-str
-list
-dict
-assert
-json
-os
-cowsay
-
-# basic modules: dependencies
-param
-http
-advise
-ui
-ps1env
-
-# modules
-static-build
-ccmd
-xdk
-zuz
-el
-
-# Apps
-tldr
-proxy
-theme
-
-# web clients
-ali
-gitee
-"
-
-
+    return 1
+}
 
 lsmod(){
-    {
-        case "$1" in
-            core)   printf "%s" "$core_mod_list" ;;
-            all)    printf "%s" "$mod_list" ;;
-            *)      printf "%s" "$mod_list" | grep "$1" ;;
-        esac
-    } | \
+    local fp
+    fp="$(lsmod_getfp)" || {
+        printf "Cannot find file modlist." >&3
+        return
+    }
+
+    local mode="${1:-all}"
     while read -r line; do
         [ "${line#\#}" != "$line" ] && continue
         [ "$line" = "" ] && continue
-        printf "%s\n" "$line"
-    done 2>/dev/null
+        case "$mode" in
+            core)   [ "$line" != "${line#+}" ] && printf "%s\n" "${line#+}" ;;
+            all)    printf "%s\n" "${line#+}" ;;
+            *)      [ "$line" != "${line#*${mode}*}" ] && printf "%s\n" "${line#+}" ;;
+        esac
+    done <"$(x wsroot)/modlist" 2>/dev/null
 }
 
 lsmod "$@"
