Squashed 'mod/x-cmd/' changes from 92426bd9..e451ab34
e451ab34 ...
7b936ccd ...
73a505cd ...

git-subtree-dir: mod/x-cmd
git-subtree-split: e451ab349e17faa13ffc6cb2bc66ce3cd29b0cae

diff --git a/_v0/boot b/_v0/boot
--- a/_v0/boot
+++ b/_v0/boot
@@ -3,9 +3,13 @@
 # Section: initrc, consider external module.
 ___x_cmd_boot(){
     local subcmd="$1"
+    if ! mkdir -p "$HOME/.x-cmd/.boot"; then
+        printf "boot abort for mkdir fails: %s\n" "$HOME/.x-cmd/.boot" >/dev/stderr
+        return 1
+    fi
+
     case "$subcmd" in
         setup)
-            mkdir -p "$HOME/.x-cmd/.boot"
             cat > "$HOME/.x-cmd/.boot/boot" <<A
 # Do NOT modify manually for this file is auto generated by command: x boot setup
 
@@ -18,7 +22,7 @@ else
     return 1
 fi
 
-[ -f "$___X_CMD_ROOT/.boot/mod" ] && x boot mod load
+[ -f "$HOME/.x-cmd/.boot/mod" ] && x boot mod load
 A
             (
                 if [ "$BASH_VERSION" ]; then        CAN="$HOME/.bashrc"
@@ -28,7 +32,7 @@ A
                 else                                CAN="$HOME/.shinit"
                 fi
 
-                X_STR="[ -f \"\$HOME/.x-cmd/.boot/boot\" ] && . \"\$HOME/.x-cmd/.boot\""
+                X_STR="[ -f \"\$HOME/.x-cmd/.boot/boot\" ] && . \"\$HOME/.x-cmd/.boot/boot\""
                 IFS=" "
                 for i in $CAN; do
                     if grep -F "$X_STR" "$i" >/dev/null; then
@@ -41,8 +45,7 @@ A
             )
             ;;
         mod)    shift
-
-                local ___X_CMD_ROOT_MOD="$___X_CMD_ROOT/.boot.mod"
+                local ___X_CMD_ROOT_MOD="$___X_CMD_ROOT/.boot/mod"
                 case "$1" in
                     path)       printf "%s" "$___X_CMD_ROOT_MOD" ;;
                     add|+)      shift
@@ -52,7 +55,7 @@ A
                                         if [ "$s" != "${s#|$mod|}" ]; then
                                             printf "%s\n" "$s"
                                         fi
-                                    done >> "$X_CMD_SRC_PATH/.init.rc"
+                                    done >> "$___X_CMD_ROOT_MOD"
                                 ) ;;
                     del|-)      shift
                                 (
@@ -68,11 +71,10 @@ A
                                 )
                                 ;;
                     load)       eval xrc "$(tr '\n' ' ' <"$___X_CMD_ROOT_MOD" | tr -d '|')" ;;
-                    ls|*)       cat "$___X_CMD_ROOT_MOD" ;;
+                    which)      printf "%s\n" "$___X_CMD_ROOT_MOD"    ;;
+                    cat|ls|*)       cat "$___X_CMD_ROOT_MOD" 2>/dev/null ;;
                 esac
                 ;;
-        # which)  printf "%s\n" "$X_CMD_SRC_PATH/.init.rc"    ;;
-        # cat|*)  cat "$X_CMD_SRC_PATH/.init.rc" 2>/dev/null  ;;
     esac
 }
 
