Squashed 'mod/proxy/' changes from 5bbce908..ce0edb76
ce0edb76 update if have no command
7bf06e6c remove: proxy_go & proxy_pip gen
2bd2ec31 update testcase to test advise json
a0c6ae9d update testcase
4a6f4bc0 add backup and rollback function
d61d830f update: all testcase && review the code by myself
12f03bc6 update: cargo testcase
db92d176 add: cargo proxy
2d9db903 update: update yum way
7e0cfc19 update: apk proxy set and reset way
2c146649 update: brew way
b3c8b116 update: pip way
eedf75a3 add: Reference
01e7769c add: Reference
3e5394e6 fix: use awk but not bc
de9aceb7 fix: version >= 1.13 use go env
e4a9c1df add: testcase for npm
ff90a0ab fix: If there is no root permission, use sudo
e2de380e update: to source the plugin file at the first time

git-subtree-dir: mod/proxy
git-subtree-split: ce0edb7617f90554b6103137b7cf6a07fd8dfaaf

diff --git a/_v0/cargo b/_v0/cargo
--- a/_v0/cargo
+++ b/_v0/cargo
@@ -2,4 +2,91 @@
 
 # https://cargo.budshome.com/reference/source-replacement.html#:~:text=目前国内%20cargo,镜像源有：中国科学技术大学源、上海交通大学源、清华大学源，以及%20rustcc%20社区源%E3%80%82
 
+proxy_cargo(){
+    param:dsl <<A
+subcommands:
+    url             "Provide url of mirror candidates"
+    get             "Get the mirror"
+    replace         "Reet the download mirror"
+    rollback        "Set the download mirror"
+A
+    param:run
+    
+    if ! command -v cargo >/dev/null; then
+        proxy_log error "command not found: cargo"
+        return 1
+        elif [ -n "$PARAM_SUBCMD" ]; then
+        "proxy_cargo_${PARAM_SUBCMD}" "$@"
+    else
+        proxy_cargo _param_help_doc  >&2
+    fi
+}
 
+proxy_cargo_url(){
+    param:dsl <<A
+subcommands:
+    ustc           "USTC mirror"
+    official       "Official mirror"
+A
+    param:run
+    
+    case "$PARAM_SUBCMD" in
+        ustc)       printf "mirrors.ustc.edu.cn" ;;
+        official)   printf "dl-cdn.alpinelinux.org" ;;
+        *)
+            printf "Unknown mirror: %s" "$PARAM_SUBCMD" >&2
+            proxy_cargo_url _param_help_doc  >&2
+        ;;
+    esac
+}
+
+proxy_cargo_replace() {
+    param:dsl <<A
+subcommands:
+    ustc           "USTC mirror"
+    official       "Official mirror"
+A
+    param:run
+    
+    local bak_dir
+    bak_dir="$HOME/.x-cmd/proxy/.backup/cargo"
+    mkdir -p "$bak_dir"
+    
+    local src_fp
+    local bak_fp
+    src_fp="$HOME/.cargo/config"
+    bak_fp="$bak_dir/config.$(date +%Y%M%d_%0H%m%S).bak"
+    
+    proxy_log info "Backing up $src_fp to $bak_fp"
+    if [ -f "$src_fp" ]; then
+        cp "$src_fp" "$bak_fp"
+    else
+        proxy_log warn "No $src_fp found"
+        touch "$bak_fp"
+    fi
+    
+    printf "[source.crates-io]
+replace-with = 'tuna'
+[source.tuna]
+registry = \"https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git\"
+    " > "$src_fp"
+}
+
+proxy_cargo_rollback() {
+    param:void
+    
+    local src_fp
+    src_fp="$HOME/.cargo/config"
+    
+    local bak_dir
+    local bak_fp
+    bak_dir="$HOME/.x-cmd/proxy/.backup/cargo"
+    bak_fp="$bak_dir/$(ls -t "$bak_dir" | head -n 1)"
+    
+    if [ -f "$bak_fp" ]; then
+        proxy_log info "Rollback from $bak_fp"
+        cp "$bak_fp" "$src_fp"
+    else
+        proxy_log info "No backup file found in $bak_dir"
+    fi
+}
diff --git a/_v0/gem b/_v0/gem
--- a/_v0/gem
+++ b/_v0/gem
@@ -1,5 +1,5 @@
 # shellcheck shell=sh disable=SC3043
-
+# reference https://zhuanlan.zhihu.com/p/90508170
 # gem sources --add https://gems.ruby-china.com/ --remove https://rubygems.org/
 
 proxy_gem(){
@@ -11,8 +11,8 @@ subcommand:
 A
 
     # if ! brew --version >/dev/null; then
-    if ! command -v npm >/dev/null; then
-        printf "gem NOT exists."
+    if ! command -v gem >/dev/null; then
+        proxy_log error "command not found: gem"
         return 1
     elif [ -n "$PARAM_SUBCMD" ]; then
         "proxy_gem_${PARAM_SUBCMD}" "$@"
@@ -64,6 +64,3 @@ proxy_gem_unset() {
     param:void
     proxy_gem_set   official
 }
-
-# reference https://zhuanlan.zhihu.com/p/90508170
-
diff --git a/_v0/yum b/_v0/yum
--- a/_v0/yum
+++ b/_v0/yum
@@ -1,1 +1,78 @@
 # shellcheck shell=sh disable=SC3043
+
+# For alpine users
+# Reference: https://blog.csdn.net/qq_33657251/article/details/107526842
+
+proxy_yum(){
+    param:dsl <<A
+subcommands:
+    url             "Provide url of mirror candidates"
+    get             "Get the mirror"
+    rollback        "Reet the download mirror"
+    replace         "Set the download mirror"
+A
+    param:run
+    
+    if ! command -v yum >/dev/null; then
+        proxy_log error "command not found: yum"
+        return 1
+    elif [ -n "$PARAM_SUBCMD" ]; then
+        proxy_yum_"${PARAM_SUBCMD}" "$@"
+    else
+        proxy_yum _param_help_doc  >&2
+    fi
+}
+
+proxy_yum_url(){
+    param:dsl <<A
+subcommands:
+    ustc           "USTC mirror"
+    official       "Official mirror"
+A
+    param:run
+    
+    case "$PARAM_SUBCMD" in
+        ustc)       printf "https://mirrors.tuna.tsinghua.edu.cn" ;;
+        official)   printf "http://mirror.centos.org" ;;
+        *)          
+                    printf "Unknown mirror: %s" "$PARAM_SUBCMD" >&2
+                    proxy_yum_url _param_help_doc  >&2
+                    ;;
+    esac
+}
+
+proxy_yum_replace() {
+    param:dsl <<A
+subcommands:
+    ustc           "USTC mirror"
+    official       "Official mirror"
+A
+    param:run
+
+    local src_dir
+    src_dir="/etc/yum.repos.d"
+
+    ___proxy_backup $src_dir yum
+
+    proxy_log info "Setting mirror to $PARAM_SUBCMD"
+
+    sed -e 's|^mirrorlist=|#mirrorlist=|g' \
+        -e 's|^#baseurl=http://mirror.centos.org/altarch/|baseurl=https://mirrors.tuna.tsinghua.edu.cn/centos-altarch/|g' \
+        -e 's|^#baseurl=http://mirror.centos.org/$contentdir/|baseurl=https://mirrors.tuna.tsinghua.edu.cn/centos-altarch/|g' \
+        -i.bak \
+        ${src_dir}/CentOS-*.repo
+
+    proxy_log "$(tail -n 5 /etc/yum.repos.d/CentOS-*Base*.repo)"
+
+    proxy_log info "Restarting yum"
+    yum makecache
+
+    proxy_log "$(tail -n 5 /etc/yum.repos.d/CentOS-*Base*.repo)"
+}
+
+proxy_yum_rollback() {
+    param:void
+    ___proxy_rollback /etc/yum.repos.d yum
+    yum makecache
+    proxy_log "$(tail -n 5 /etc/yum.repos.d/CentOS-*Base*.repo)"
+}
