Squashed 'mod/proxy/' changes from c37bb421..93ce86c7
93ce86c7 update testcase for 'x test'
7892427f rollback ls
01aa6fe9 update: add all tutorial todo
87c7de70 update: all proxy module
99efe5b9 update: command not found
7437d379 update: testcase
c8f2cabd update : description for npm && fix proxy set
ea80da36 update : advise gen
54291abb update : gem way
076e4bcd update yum centos 7 8 arm version
828c109b finish cargo in different mirrors
7793b6ca remove: rollback_use function
2434f6a7 update: use Section and EndSection
1d215538 update: add rollback to cargo

git-subtree-dir: mod/proxy
git-subtree-split: 93ce86c71475883afcb85b7b9247be9a63878ff6

diff --git a/_v0/gem b/_v0/gem
--- a/_v0/gem
+++ b/_v0/gem
@@ -7,16 +7,19 @@ proxy_gem(){
 subcommand:
     url        "Provide url of mirror candidates"
     set        "Setting the mirror"
+    get        "Get current mirror"
     unset      "Reset the source to the original official"
 A
+    param:run
 
-    # if ! brew --version >/dev/null; then
     if ! command -v gem >/dev/null; then
-        proxy_log error "command not found: gem"
+        proxy_log error "command not found: gem, you should install gem in your system."
         return 1
     elif [ -n "$PARAM_SUBCMD" ]; then
         "proxy_gem_${PARAM_SUBCMD}" "$@"
     else
+        proxy_log info "Current mirror is: "
+        proxy_gem get
         proxy_gem _param_help_doc  >&2
     fi
 
@@ -25,9 +28,11 @@ A
 proxy_gem_url(){
     param:dsl <<A
 subcommand:
-    ruby-china              "ruby china"
-    official                "Official"
+    ruby-china|cn           "ruby china mirror"
+    official                "Official mirror"
 A
+    param:run
+
     case "$PARAM_SUBCMD" in
         # https://gems.ruby-china.com
         ruby-china|cn)          printf https://gems.ruby-china.com                  ;;
@@ -36,31 +41,37 @@ A
     esac
 }
 
-
-_proxy_gem_url_custom(){
-    param:dsl <<A
-option:
-    #1          "URL"      =~       https?://.+
-A
-    printf "%s" "${1:?Impossible}"
+proxy_gem_get(){
+    param:void
+    gem sources -l | grep "http"
 }
-
 
 proxy_gem_set() {
     param:dsl <<A
 subcommand:
-    ruby-china              "ruby china"
+    ruby-china|cn           "ruby china mirror"
     official                "Official"
 A
+    param:run
+
     local url
-    
     if url="$(proxy_gem_url "${PARAM_SUBCMD:-ruby-china}")"; then
-        printf "Setting proxy_gem mirror:\n    %s" "$url" >&2
-        gem sources --add "$url" --remove https://rubygems.org/
+        printf "Setting proxy_gem mirror:\n    %s\n" "$url" >&2
+
+        for i in $(proxy_gem_get); do
+            gem sources -r "$i"
+        done
+        gem sources --add "$url"
     fi
 }
 
 proxy_gem_unset() {
     param:void
     proxy_gem_set   official
+}
+
+proxy_gem_tutorial(){
+    param:void
+    cat <<A
+A
 }
diff --git a/_v0/go b/_v0/go
--- a/_v0/go
+++ b/_v0/go
@@ -4,18 +4,31 @@
 proxy_go(){
     param:dsl <<A
 subcommands:
-    auto|autoset                       "Set the goproxy and gosumdb to recommended mirror"
-    unset|reset                        "Reet the download mirror"
-    gosumdb|sumdb|sum|gosum            "operations for gosumdb"
-    set                                "Set the download mirror"
-    service                            "Provide mirror service in docker or native binary"
-    version                            "Show version"
-    tutorial|xman                      "Tutorial for setting goproxy "                      
-    help                               "Show help"
+    get                  "Get current proxy"
+    auto                 "Set the goproxy and gosumdb to recommended mirror"
+    unset                "Set the download mirror"
+    gosumdb              "Operations for gosumdb"
+    set                  "Set the download mirror"
+    service              "Provide mirror service in docker or native binary"
+    tutorial             "Tutorial for setting goproxy "                      
 A
     param:run
 
-    "proxy_go_${PARAM_SUBCMD}" "$@"
+    if ! command -v go >/dev/null; then
+        proxy_log error "command not found: go, you should install go in your system."
+        return 1
+    elif [ -n "$PARAM_SUBCMD" ]; then
+        "proxy_go_${PARAM_SUBCMD}" "$@"
+    else
+        proxy_log info "Current GOPROXY is:    "
+        proxy_go get
+        proxy_go _param_help_doc  >&2
+    fi
+}
+
+proxy_go_get(){
+    param:void
+    go env | grep -i GOPROXY
 }
 
 # Using web to judge instead of dig command
@@ -47,12 +60,12 @@ ___proxy_go_set(){
     else
         code="
     go env -w GO111MODULE=on
-    go env -w GOPROXY="$url,direct"
+    go env -w GOPROXY="${url},direct"
 "
     fi
 
     eval "$code"
-    printf "%s\n%s" "Seting the GORPOXY and GO111MODULE env with following code:" "$code" >&2
+    printf "%s\n    %s\n" "Seting the GORPOXY and GO111MODULE env." "$(proxy_go_get)" >&2
 }
 
 proxy_go_set(){
@@ -67,8 +80,8 @@ A
 
     case "${PARAM_SUBCMD:-qiniu}" in
         ali|aliyun)            ___proxy_go_set    https://mirrors.aliyun.com/goproxy/ ;;
-        goproxy|goproxy.cn)    ___proxy_go_set    https://goproxy.io/zh/ ;;
-        qiniu|io|goproxy.io)   ___proxy_go_set    https://goproxy.cn ;;
+        goproxy|goproxy.cn)    ___proxy_go_set    https://goproxy.io/zh/              ;;
+        qiniu|io|goproxy.io)   ___proxy_go_set    https://goproxy.cn                  ;;
         *) ;;
     esac
 }
@@ -76,8 +89,8 @@ A
 proxy_go_gosumdb(){
     param:dsl <<A
 subcommands:
-    set                                "Set the download mirror"
-    unset|reset|clear                  "Reset the download mirror"
+    set                    "Set the download mirror"
+    unset                  "Unset the download mirror"
 A
     param:run
 
@@ -101,18 +114,15 @@ proxy_go_unset(){
     param:void
     local code
 
+    # TODO: To be optimized.
     if [ "$(go version | awk '{ a=substr($3, 3); if(a<1.13) print 1; else print 0 }')" = 1 ]; then
-        code="
-    export GOPROXY=
-"
+        code="export GOPROXY="
     else
-        code="
-    go env -u GOPROXY
-"
+        code="go env -u GOPROXY"
     fi
 
     eval "$code"
-    printf "Unset the GOPROXY env.\n" >&2
+    printf "Unset the GOPROXY env.\n    %s\n" "$(proxy_go_get)" >&2
 }
 
 # help doc: https://goproxy.io/zh/docs/enterprise.html
@@ -133,17 +143,17 @@ proxy_go_tutorial(){
     cat <<A
 Windows Powershell:
 
-Format: \$env:GOPROXY = <url>
+Format: 
+    \$env:GOPROXY = <url>
 
 Example:
-\$env:GOPROXY = "https://goproxy.cn"
+    \$env:GOPROXY = "https://goproxy.cn"
 
 Windows:
-
-1. 右键 我的电脑 -> 属性 -> 高级系统设置 -> 环境变量
-2. 在 “[你的用户名]的用户变量” 中点击 ”新建“ 按钮
-3. 在 “变量名” 输入框并新增 “GOPROXY”
-4. 在对应的 “变量值” 输入框中新增 “https://goproxy.io,direct”
-5. 最后点击 “确定” 按钮保存设置    
+    1. 右键 我的电脑 -> 属性 -> 高级系统设置 -> 环境变量
+    2. 在 “[你的用户名]的用户变量” 中点击 ”新建“ 按钮
+    3. 在 “变量名” 输入框并新增 “GOPROXY”
+    4. 在对应的 “变量值” 输入框中新增 “https://goproxy.io,direct”
+    5. 最后点击 “确定” 按钮保存设置    
 A
 }
