Squashed 'mod/gitee/' changes from 6c50050..d3bb671
d3bb671 fix bug

git-subtree-dir: mod/gitee
git-subtree-split: d3bb671b7134f59910eb9b00b94ab75f3ececbe4

diff --git a/_v0/issue b/_v0/issue
--- a/_v0/issue
+++ b/_v0/issue
@@ -167,6 +167,12 @@ subcommands:
     update          "update a comment"
     delete          "delete a comment"
 '
+    param:run
+    if [ -z "$PARAM_SUBCMD" ]; then
+        echo "subcommand not found. show help." >&2
+        return 0
+    fi
+    "gt_issue_comment_$PARAM_SUBCMD" "$@"
 }
 
 gt_issue_comment_ls(){
