Squashed 'mod/gitee/' changes from e7f9fa64..528c7582
528c7582 add ui select
7d2964e2 member done
1732c957 fix git token save

git-subtree-dir: mod/gitee
git-subtree-split: 528c758254f336092595be0134c23f93b29e4c3c

diff --git a/_v0/repo b/_v0/repo
--- a/_v0/repo
+++ b/_v0/repo
@@ -13,6 +13,7 @@ subcommands:
     clear           "clear repo"
     issue           "get repo issue"
     release         "release"
+    review          "review repo"
 '
     param:run
 
@@ -54,7 +55,7 @@ option:
     --no_auto_init          "auto init README"
     --gitignore_template    "Git Ignore"                    <>=""
     --license_template      "license"                       <>=""
-    --paths                  "repo path"                     <>=""
+    --paths                 "repo path"                     <>=""
     #n                      "repo names"
 '
     param:run
@@ -78,14 +79,19 @@ option:
     local name
     for name in "$@"; do
         {
-            # ___gt_post_json "/v5/user/repos" name has_issues has_wiki private 2>/dev/null
-            ___gt_post_json "/v5/user/repos" name description homepage has_issues has_wiki can_comment auto_init \
-                gitignore_template license_template path="$paths" private 2>/dev/null
-            code=$?
-            if [ $code -ne 0 ]; then
-                gt_log error "Creating repo failure: $name. Code is $code. "
-                # ___gt_resp_header "" >&2
-                return $code
+            local data repo_id url repo_owner
+            data=$(___gt_post_json "/v5/user/repos" name="${name##*/}" description homepage has_issues has_wiki can_comment \
+            auto_init gitignore_template license_template path="$paths" private 2>/dev/null)
+            ___json_awk_get repo_id=.id url=.html_url repo_owner=.owner.login <<A
+            $data
+A
+            if [ -n "$repo_id" ];then
+                ui tf "true" "Creating repo $name success
+- repo_id:$repo_id
+- url:$url
+- repo_owner:$repo_owner" 
+            else
+                gt_log error "Creating repo failure: $name. Code is $code. " 
             fi
         }
     done
@@ -215,13 +221,7 @@ option:
 # gt repo list --access inner-source <owner>
 # gt enterprise repo list
 gt_repo_ls() {
-    param:scope     "gitee/$O"
-    param:dsl       '
-options:
-    #1              "Provide owner"
-'
-    param:run
-
+    param:void
     local owner
     owner="$1"
 
@@ -266,12 +266,18 @@ options:
     #n      "Provide repo list"    <>
 '
     param:run
+    local confirm
+    confirm=$(ui select "text" "Are you sure you want to delete repo $*" "yes" "no")
+    [ "$confirm" = "no" ] && return
     local i
     for i in "$@"; do
         ___gt_param_normalize_repo "$i"
-        gt_log info "Deleting repo: $owner_repo"
-        ___gt_delete "/v5/repos/$owner_repo" >/dev/null ||
+        ___gt_delete "/v5/repos/$owner_repo" >/dev/null 
+        if [ $? -eq 0 ]; then
+            ui tf "true" "deleted repo $i"
+        else
             gt_log error "Code is $?. Deleting repo failure: $i. Probably because it desn't exists."
+        fi
     done
 }
 
@@ -284,7 +290,11 @@ options:
     param:run
 
     gt_param_init_owner_repo
-    ___gt_put_json "/v5/repos/${owner_repo}/clear"
+    local confirm
+    confirm=$(ui select "text" "Are you sure you want to clear repo ${owner_repo}" "yes" "no")
+    [ "$confirm" = "no" ] && return
+    ___gt_put_json "/v5/repos/${owner_repo}/clear" && ui tf "true" "Successfully clear ${owner_repo}" && return
+    gt_log error "clear repo failure: $owner_repo"
 }
 
 gt_repo_review(){
