Squashed 'mod/gt/' changes from cc6c1592..9dc80fd1
9dc80fd1 style: update code format
3bf1d3bc style: update code format
9d8fa8e5 feat(list): support multi page mode
bd05fddf update http json
f82bf322 update page x ja
de20dc12 update page
e2e20464 fix(http): update post put patch exec way
6f6b257c test(repo): add replace `sed`
12fa69df feat: done release
d7f26313 fix(utils): update get owner repo
9e295d98 fix: fix token default
6ce194c6 feat(event): init event module
c75679d2 refactor(current): update current user usage
6b3a56d3 refactor(current): update current user usage
36a79078 ...
c97dc4b0 ...
7d4ff3bd refactor(repo): add status handler
67448565 refactor(utils): update table util
93f8e8e4 style: update code format
892b9eeb fix(theme): rename ui to add x-cmd prefix
8e528a95 style: update code format
2917e10b fix: dict -> ___x_cmd_dict os -> ___x_cmd_os
129e1b41 fix($O): remove GITEE_DEFAULT
b74e5c10 chore(types): update types
7b685ac5 feat(table): update table use util func
4f425866 chore(user): update user type match multiple user
7e8306ce refactor(gt): refactor $O
3ecf4f9f feat(release): add repo release create
85577ce0 chore: update empty subcmd description
027edc84 style(help): update subcmd not found help
719bcc5c chore(gt): update http put subcmd type
8bc5a800 fix(gt): update path option define of zsh
e4c08755 fix(gt): update path config define
ffb3dda5 test: move test file to dev
80b1dc5d fix(advise): fix gt advise undefine function
817f609e style(type): update gt type code format
e9f18bfa ci(test): add test github action

git-subtree-dir: mod/gt
git-subtree-split: 9dc80fd19e2cbc7a8cd05ead44dd97464d0c75c3

diff --git a/lib/repo/main b/lib/repo/main
--- a/lib/repo/main
+++ b/lib/repo/main
@@ -2,7 +2,7 @@
 # shellcheck disable=SC2039,3043
 
 ___x_cmd_gt_repo(){
-    param:scope     "gitee/$O"
+    param:scope         ___x_cmd_gt
     param:subcmd ___x_cmd_gt_repo                                       \
         create          "Create repo"                                   \
         ls              "List repo of owner"                            \
@@ -16,8 +16,8 @@ ___x_cmd_gt_repo(){
     param:subcmd:try
     param:run
 
-    gt_log warn "Subcmd Not Found."
     ___x_cmd_gt_repo _param_help_doc
+    gt_log warn "Subcmd Not Found."
     return 1
 }
 
@@ -25,9 +25,7 @@ ___x_cmd_gt_repo(){
 # shellcheck disable=SC2154
 # https://gitee.com/api/v5/swagger#/postV5UserRepos
 ___x_cmd_gt_repo_create(){
-    local O="${O:-GITEE_DEFAULT}"
-
-    param:scope     "gitee/$O"
+    param:scope     ___x_cmd_gt
     param:dsl       '
 option:
     #n                      "repo names"                    <>:RepoName
@@ -44,19 +42,19 @@ option:
     --no_auto_init          "Not auto init README"
 '
     param:run
-    [ $# -eq 0 ] && gt_log error "Repo name is empty" && return 1
+    [ $# -ne 0 ] || { gt_log error "Please provide repo name"; return 1; }
 
     local private
     case "$access" in
-        public)     private=false ;;
-        private)    private=true ;;
+        public)     private=false   ;;
+        private)    private=true    ;;
     esac
     local name="%%name%%"
     local gen_gt_json
     gen_gt_json="$(
         param:option2json +name +private -access \
             has_issues=^no_issue        has_wiki=^no_wiki \
-            can_comment=^no_comment     auto_init=^no_auto_init)"
+            can_comment=^no_comment     auto_init=^^no_auto_init)"
 
     for name in "$@"; do
         printf "%s" "${gen_gt_json}" | sed s/%%name%%/"${name##%/}"/g | \
@@ -76,7 +74,7 @@ ___x_cmd_gt_repo_create_status_handler(){
     if [ -n "$repo_id" ]; then
         ___x_cmd_ui_tf true  "Creating repo $name successfully" "repo_id: $repo_id" "repo_owner: $repo_owner" "url: $url"
     else
-        ___x_cmd_ui_tf false "Creating repo failure: $name."
+        ___x_cmd_ui_tf false "Creating repo failure: $name"
         return 1
     fi
 }
@@ -87,7 +85,7 @@ ___x_cmd_gt_repo_create_status_handler(){
 ___x_cmd_gt_org_repo_create(){
     # TODO: I don't know what does path means for an organization repo
     # path is null default repo name as path
-    param:scope     "gitee/$O"
+    param:scope     ___x_cmd_gt
     param:dsl       '
 option:
     #n                      "repo names"
@@ -117,7 +115,7 @@ option:
     gen_gt_json="$(
         param:option2json +name +private -access \
             has_issues=^no_issue            has_wiki=^no_wiki \
-            can_comment=^no_comment         auto_init=^no_auto_init )"
+            can_comment=^no_comment         auto_init=^^no_auto_init )"
 
     # TODO: owner may be personal
     for name in "$@"; do
@@ -145,7 +143,7 @@ ___x_cmd_gt_org_repo_create_status_handler(){
 # https://gitee.com/api/v5/swagger#/postV5EnterprisesEnterpriseRepos
 # shellcheck disable=SC2154,SC2034
 ___x_cmd_gt_enterprise_repo_create(){
-    param:scope     "gitee/$O"
+    param:scope     ___x_cmd_gt
     param:dsl       '
 type:
     Access  =   private public innerSource
@@ -180,9 +178,10 @@ option:
     gen_gt_json="$(
         param:option2json +name +private -access \
         has_issues=^no_issue            has_wiki=^no_wiki              outsourced=^^outsourced \
-        can_comment=^no_comment         auto_init=^no_auto_init)"
+        can_comment=^no_comment         auto_init=^^no_auto_init)"
 
     for name in "$@"; do
+        # x tmpl "$gen_gt_json"  "${name##%/}" | \
         printf "%s" "${gen_gt_json}" | sed s/%%name%%/"${name##%/}"/g | \
             ___x_cmd_gt_http post "/v5/enterprises/${enterprise##*/}/repos" - | \
             ___x_cmd_gt_enterprise_repo_create_status_handler
@@ -215,11 +214,9 @@ ___x_cmd_gt_repo_ls(){
         owner_type=user
     else
         local owner="$1"
-        owner_type="$(______x_cmd_gt_owner_type_query "$owner")"
+        owner_type="$(___x_cmd_gt_owner_type_query "$owner")"
     fi
-
-    ___x_cmd_gt_"${owner_type}"_repo ls "$@" && return 0
-    return 1
+    ___x_cmd_gt_"${owner_type}"_repo ls "$@"
 }
 # EndSection
 
@@ -228,7 +225,7 @@ ___x_cmd_gt_repo_ls(){
 # shellcheck disable=SC2154,SC2034
 # TODO: https://gitee.com/api/v5/swagger#/patchV5ReposOwnerRepo need to design
 ___x_cmd_gt_repo_update(){
-    param:scope     "gitee/$O"
+    param:scope     ___x_cmd_gt
     param:dsl       '
 type:
     Access  =   public private ""
@@ -291,26 +288,32 @@ ___x_cmd_gt_repo_update_status_handler(){
 # shellcheck disable=SC2154
 # https://gitee.com/api/v5/swagger#/getV5ReposOwnerRepo
 ___x_cmd_gt_repo_info(){
-    param:scope     "gitee/$O"
+    param:scope     ___x_cmd_gt
     param:dsl       '
 options:
     #1|--repo          "Provide owner name and repo name.(default:the current user repo)"   <>:RepoName
 '
     param:run
 
-    # get owner_repo by repo
     ___x_cmd_gt_param_init_owner_repo
-    ___x_cmd_gt_http get "/v5/repos/${owner_repo}" | \
-    {
-        ___x_cmd_git_json_query_rename id=.id name=.name html_url=.html_url
-        if [ -n "$id" ]; then
-             ___x_cmd_ui_tf true    "Success" "id: $id" "name: $name" "url: $html_url"
-             return 0
-        else
-             ___x_cmd_ui_tf false   "Couldn't find any repo: $owner_repo"
-            return 1
-        fi
-    }
+
+    ___x_cmd_gt_http get "/v5/repos/${owner_repo}" | ___x_cmd_gt_repo_info_status_handler
+}
+
+# shellcheck disable=SC2154
+___x_cmd_gt_repo_info_status_handler() {
+    if [ ! -t 1 ] || [ -n "$ENFORCE_JSON" ]; then
+        cat
+        return
+    fi
+
+    ___x_cmd_git_json_query_rename id=.id name=.name html_url=.html_url
+    if [ -n "$id" ]; then
+        ___x_cmd_ui_tf true    "Success" "id: $id" "name: $name" "url: $html_url"
+    else
+        ___x_cmd_ui_tf false   "Couldn't find any repo: $owner_repo"
+        return 1
+    fi
 }
 # EndSection
 
@@ -319,7 +322,7 @@ options:
 # shellcheck disable=SC2181,SC2154
 ___x_cmd_gt_repo_rm(){
     # TODO: -y force del
-    param:scope     "gitee/$O"
+    param:scope     ___x_cmd_gt
     param:dsl       '
 options:
     #n      "Provide repo path list"    <>
@@ -342,7 +345,7 @@ options:
 # shellcheck disable=SC2181
 # https://gitee.com/api/v5/swagger#/putV5ReposOwnerRepoClear
 ___x_cmd_gt_repo_clear(){
-    param:scope     "gitee/$O"
+    param:scope     ___x_cmd_gt
     param:dsl       '
 options:
     #1|--repo          "Provide owner name and repo path.(default:the current user repo)"   <>:RepoName
@@ -366,7 +369,7 @@ options:
 # shellcheck disable=SC2154,SC2181
 # https://gitee.com/api/v5/swagger#/putV5ReposOwnerRepoReviewer
 ___x_cmd_gt_repo_review(){
-    param:scope     "gitee/$O"
+    param:scope     ___x_cmd_gt
     param:dsl       '
 options:
     #1|--repo             "Provide owner name and repo name.(default:the current user repo)"   <>:RepoName
@@ -380,15 +383,22 @@ options:
     local gen_gt_json
     gen_gt_json="$(param:option2json)"
 
-    ___x_cmd_gt_http put "/v5/repos/${owner_repo}/reviewer" "$gen_gt_json" | \
-    {
-        ___x_cmd_git_json_query_rename name=.name
-        if [ -n "$name" ]; then
-            ___x_cmd_ui_tf true   "Setuping ${owner_repo} review configure successfully"
-        else
-            ___x_cmd_ui_tf false  "Setuping repo review configure failure: ${owner_repo}"
-            return 1
-        fi
-    }
+    ___x_cmd_gt_http put "/v5/repos/${owner_repo}/reviewer" "$gen_gt_json" | ___x_cmd_gt_repo_review_status_handler
+}
+
+# shellcheck disable=SC2154
+___x_cmd_gt_repo_review_status_handler(){
+    if [ ! -t 1 ] || [ -n "$ENFORCE_JSON" ]; then
+        cat
+        return
+    fi
+
+    ___x_cmd_git_json_query_rename name=.name
+    if [ -n "$name" ]; then
+        ___x_cmd_ui_tf true   "Setuping ${owner_repo} review configure successfully"
+    else
+        ___x_cmd_ui_tf false  "Setuping repo review configure failure: ${owner_repo}"
+        return 1
+    fi
 }
 # EndSection
diff --git a/lib/utils b/lib/utils
--- a/lib/utils
+++ b/lib/utils
@@ -5,35 +5,55 @@
 # Section 2: Wrapping std/http module with object naming changing
 ############################
 ___x_cmd_gt_resp_header(){
-    http "___x_cmd_gt_${O:-GITEE_DEFAULT}" resp header "$@"
+    O="${O:-___x_cmd_gt_GITEE_DEFAULT}" ___x_cmd_http resp header "$@"
 }
 
 # TODO: Not supported yet
 ___x_cmd_gt_resp_body(){
-    http "___x_cmd_gt_${O:-GITEE_DEFAULT}" resp body "$@"
+    O="${O:-___x_cmd_gt_GITEE_DEFAULT}" ___x_cmd_http resp body "$@"
 }
-
-___x_cmd_gt_get_multi(){
+___x_cmd_gt_get_multi() {
     if [ -n "$page" ] || [ -n "$per_page" ]; then
         ___x_cmd_gt_http get "$@" page per_page
-        return "$?"
+        return
     fi
-    local i=1
-    local total_page=100000
-    while [ "$i" -le "$total_page" ]; do
-        ___x_cmd_gt_http get "$@" page="$i" per_page=100
-        total_page="$(___x_cmd_gt_resp_header "total_page")"
-        [ -z "$total_page" ] && return
-        # echo "total_page:$total_page" >&2
-        i=$((i+1))
+    local tmp
+    tmp=$(mktemp)
+    ___x_cmd_gt_http get "$@" page=1 per_page=100 >> "$tmp"
+    local next_url
+    _____x_cmd_gt_next_url
+    if [ -z "$next_url" ];then
+        cat "$tmp"
+        rm "$tmp"
+        return
+    fi
+    while [ -n "$next_url" ]; do
+        ___x_cmd_gt_http get "$next_url" >> "$tmp"
+        _____x_cmd_gt_next_url
     done
+    x ja 'BEGIN{print "["} END{print "]"}O[1]{
+    if ((V == "}") || (V == "]") || (K ~ "^[0-9]+$")) print V
+    else print K ": "V;
+    }' < "$tmp" | x jo fmt
+    rm "$tmp"
+}
+
+_____x_cmd_gt_next_url(){
+    next_url="$(___x_cmd_gt_resp_header "link")"
+    next_url="${next_url#*"rel='prev', <"}"
+    local tmp_url="${next_url%%">; rel='next'"*}"
+    if [ "$next_url" != "$tmp_url" ];then
+        next_url="${tmp_url#*'.com/api'*}"
+    else
+        next_url=""
+    fi
 }
 
 ___x_cmd_gt_http(){
-    if ! O="___x_cmd_gt_${O:-GITEE_DEFAULT}" http header get Content-Type 1>/dev/null 2>&1; then
-         O="___x_cmd_gt_${O:-GITEE_DEFAULT}" http header put Content-Type application/json
+    if ! O="${O:-___x_cmd_gt_GITEE_DEFAULT}" ___x_cmd_http header get Content-Type 1>/dev/null 2>&1; then
+        O="${O:-___x_cmd_gt_GITEE_DEFAULT}" ___x_cmd_http header put Content-Type application/json
     fi
-    O="___x_cmd_gt_${O:-GITEE_DEFAULT}" http "$@"
+    O="${O:-___x_cmd_gt_GITEE_DEFAULT}" ___x_cmd_http "$@"
 }
 
 ############################
@@ -45,6 +65,7 @@ alias ___x_cmd_gt_param_init_owner_repo='
     ___x_cmd_gt_param_normalize_repo  || return
 '
 
+# shellcheck disable=SC2154,SC2034
 ___x_cmd_gt_param_normalize_repo(){
     local op="$repo"
     [ -z "$op" ] && op="$1"
@@ -53,52 +74,32 @@ ___x_cmd_gt_param_normalize_repo(){
         owner_repo="$(printf "%s" "$op")"
         ;;
     "")
-        local _owner
-        local _repo
-        _owner="$(___x_cmd_gt_current_owner)"
-        if [ -z "$_owner" ]; then
-            printf "No owner provided. Default owner NOT set.\n" >&2
-            return 1
-        fi
-
-        _repo="$(___x_cmd_gt_current_repo)"
-        if [ -z "$_repo" ]; then
-            printf "No repo provided. Default repo NOT set.\n" >&2
-            return 1
-        fi
-
-        owner_repo="$(printf "%s/%s" "$_owner" "$_repo")"
+        owner_repo="$(_____x_cmd_git_repo)"
         ;;
     *)
-        local _owner
-        _owner="$(___x_cmd_gt_current_owner)"
-        if [ -z "$_owner" ]; then
+        ___x_cmd_gt_current_owner 1>/dev/null
+        if [ -z "$___X_CMD_GITEE_DEFAULT_OWNER" ]; then
             printf "No owner provided. Default owner not set.\n" >&2
+            return 1
         fi
-        owner_repo="$(printf "%s" "$_owner/$op")"
+        owner_repo="$(printf "%s" "$___X_CMD_GITEE_DEFAULT_OWNER/$op")"
         ;;
     esac
-}
-
-### Repo #1
-
-___x_cmd_gt_parse_owner_repo(){
-    local O="${O:-GITEE_DEFAULT}"
-    if [ -z "$repo" ]; then
-        repo="$(___x_cmd_gt_current_repo)"
-    fi
-    # if [[ "$repo" = */* ]]; then
-    if str_regex "$repo" "/"; then
-        owner=${repo%%/*}
-        repo=${repo##*/}
-    fi
-    if [ -z "$owner" ]; then
-        owner="$(___x_cmd_gt_current_owner)"
-    fi
 }
 
 ___x_cmd_gt_default(){
     param_default "$@" 2>/dev/null || return 1
 }
 
+___gt_ui_mutual(){
+    if [ ! -t 1 ] || [ -n "$ENFORCE_JSON" ] ; then
+        "$@"
+    else
+        # run ui table
+        eval "$(cat)"
+    fi
 
+    local ___gt_exit_code="$?"
+    [ "$___gt_exit_code" -eq 0 ] || gt_log error "${___gt_error_msg:-"Couldn't find any data"}"
+    return "$___gt_exit_code"
+}
