...

diff --git a/mod/awscli/latest b/mod/awscli/latest
--- a/mod/awscli/latest
+++ b/mod/awscli/latest
@@ -1,13 +1,21 @@
 # Author:       Li Junhao       l@x-cmd.com
 # shellcheck    shell=sh        disable=SC3043,SC2164,SC1091     # xrc
 
-___x_cmd_ucloud(){
-    ___x_cmd___ucloud_origin "$@"
+___x_cmd_awscli(){
+    ___x_cmd___awscli_origin "$@"
 }
 
-___x_cmd___ucloud_origin(){
-    x pkg xbin init ucloud "" ___x_cmd___ucloud_origin || return
-    ___x_cmd___ucloud_origin "$@"
+___x_cmd___awscli_origin(){
+    if ! x pipx install awscli; then
+        x:error "Pip Installation failure."
+        return 1
+    fi
+
+    ___x_cmd___awscli_origin(){
+        command aws "$@"
+    }
+
+    ___x_cmd___awscli_origin "$@"
 }
 
-xrc setmain ___x_cmd_ucloud
+xrc setmain ___x_cmd_awscli
diff --git a/mod/ffmpeg/latest b/mod/ffmpeg/latest
--- a/mod/ffmpeg/latest
+++ b/mod/ffmpeg/latest
@@ -1,31 +1,24 @@
-# shellcheck shell=sh
-# shellcheck disable=SC2039,3043
+# Author:       Li Junhao       l@x-cmd.com                 # xrc
+# shellcheck    shell=sh        disable=SC2039,3043
 
-# author:       Li Junhao           l@x-cmd.com
+___x_cmd_ffmpeg(){
+    local op="$1"
 
-xrc param
-
-
-___x_cmd_ff(){
-    local op
-    op="$1"
-    # file to file
     case "$op" in
-        show)       ___x_cmd_ff_show "$@" ;;
-        convert)    ___x_cmd_ff_convert "$@" ;;
-        play)       ___x_cmd_ff_play "$@" ;;
-        probe)      ___x_cmd_ff_probe "$@" ;;
-        -*)         ___x_cmd_ffmpeg_origin "$@" ;;
-        *)
-            : detect input and output
-            : then convert the input to output
-            ;;
+        show)       shift; ___x_cmd_ffmpeg_show "$@" ;;
+        convert)    shift; ___x_cmd_ffmpeg_convert "$@" ;;
+        play)       shift; ___x_cmd_ffmpeg_play "$@" ;;
+        *)          shift; ___x_cmd_ffmpeg_origin "$@" ;;
     esac
 
 }
 
 ___x_cmd_ffmpeg_origin(){
-    command ffmpeg "$@"
+    if ! ___x_cmd_pkg_xbin_init ffmpeg "N-105323-gdd17c86aa1-tessus" "" ___x_cmd_ffmpeg_origin; then
+        x:error "Fail to pkg_xbin_init ffmpeg"
+        return 1
+    fi
+    ___x_cmd_ffmpeg_origin "$@" 2>/dev/null
 }
 
 ___x_cmd_ffmpeg_show(){
@@ -39,3 +32,6 @@ ___x_cmd_ffmpeg_show(){
 
 }
 
+# EndSection
+
+xrc setmain ___x_cmd_ffmpeg
diff --git a/mod/gitlab/latest b/mod/gitlab/latest
--- a/mod/gitlab/latest
+++ b/mod/gitlab/latest
@@ -1,13 +1,67 @@
-# Author:       Li Junhao       l@x-cmd.com
-# shellcheck    shell=sh        disable=SC3043,SC2164,SC1091     # xrc
+# shellcheck shell=sh
+# shellcheck disable=SC2039,3043
 
-___x_cmd_ucloud(){
-    ___x_cmd___ucloud_origin "$@"
+# author:       Li Junhao           edwin.jh.lee@gmail.com    edwinjhlee.github.io
+# maintainer:   Li Junhao
+
+# loading dependencies
+xrc http param ui
+xrc ui/lib/table gh/lib/resource
+
+xrc:inner:lib gitlab utils config current token user issue/main project/main project/member groups/main groups/member
+
+x log init gitlab
+___x_cmd_gitlab(){
+    param:subcmd ___x_cmd_gitlab        \
+        user        "user"              \
+        project     "project command"   \
+        config      "save, load, which" \
+        current     "current user"      \
+        groups      "groups manage"     \
+        subgroup    "subgroups manage"  \
+        issue       "issue manage"      \
+        token       "set token"
+    param:subcmd:try
+    param:run
+
+    ___x_cmd_gitlab _param_help_doc
+    gitlab_log warn "Subcmd Not Found."
+    return 1
 }
 
-___x_cmd___ucloud_origin(){
-    x pkg xbin init ucloud "" ___x_cmd___ucloud_origin || return
-    ___x_cmd___ucloud_origin "$@"
+
+############################
+# Section 10: Instantiation
+############################
+___x_cmd_gitlab_make(){
+    param:void
+
+    local O="___x_cmd_gitlab_${1:?Provide client name by O environment}"
+
+    ___x_cmd_http make  'https://gitlab.com/api/v4'
+    ___x_cmd_http header put type  "application/json;charset=utf-8"
+
+    local token
+    token="$(___x_cmd_gitlab_config_get "oauth_token")"
+
+    if [ -n "$token" ]; then
+        ___x_cmd_http header put "PRIVATE-TOKEN" "$token"
+        ___x_cmd_gitlab_current_owner 1>/dev/null || return 1
+        gitlab_log info "Hi $___X_CMD_GITLAB_DEFAULT_OWNER! You've successfully authenticated."
+        return 0
+    fi
+
+    local info
+    info=$(printf "\n%s %s \n%s" \
+         "$(___x_cmd_ui yellow 'You need run command to add token:')" \
+         "$(___x_cmd_ui bold cyan "\`gitlab token <token>\`")" \
+         "$(___x_cmd_ui 'https://gitee.com/profile/personal_access_tokens')")
+    gitlab_log warn "Token is null.${info}"
 }
 
-xrc setmain ___x_cmd_ucloud
+if [ -z "$DO_NOT_INIT_GITLAB_DEFAULT" ]; then
+    ___x_cmd_gitlab_make "GITLAB_DEFAULT" && DO_NOT_INIT_GITLAB_DEFAULT="true"
+fi
+
+xrc setmain ___x_cmd_gitlab
+
diff --git a/mod/path/latest b/mod/path/latest
--- a/mod/path/latest
+++ b/mod/path/latest
@@ -1,52 +1,17 @@
-# Author:       Li Junhao   l@x-cmd.com             # xrc
-# shellcheck    shell=sh    disable=SC3043,SC1091
+# Author:       Li Junhao           l@x-cmd.com         # xrc
+# shellcheck    shell=sh            disable=SC3043
 
-___x_cmd_tmp(){
+___x_cmd_path(){
     case "$1" in
-        path_)          shift 1; ___x_cmd_tmp_path_ "$@" ;;
-
-        path)           shift 1; ___x_cmd_tmp_path "$@" ;;
-        root)           shift 1; ___x_cmd_tmp_root "$@" ;;
-
-        # create file
-        touch)          shift 1; ___x_cmd_tmp_touch "$@" ;;
-
-        # create dir
-        dir)            shift 1; ___x_cmd_tmp_dir "$@" ;;
-
-        *)              ___x_cmd_tmp_path "$@" ;;
+        add|shift|unshift|push|pop|ls|uniq|rm|rm_by_prefix|rm_by_suffix|up_or_unshift|down_or_push|add_existed_folder|_x_cmd_advise_json)
+            local op="$1"; shift; "___x_cmd_path_$op" "$@" ;;
+        "") ___x_cmd_path_ls "$@" ;;
+        --help|-h|help)
+            ___x_cmd_path_help ;;
+        *)  printf "%s" "Can't support arg: $1" >&2 ;;
     esac
 }
 
-___x_cmd_tmp_path(){
-    ___x_cmd_tmp_path_ "$@" || return
-    printf "%s\n" "$___X_CMD_TMP_PATH_"
-}
+xrc:mod:lib path    util ls
 
-___x_cmd_tmp_path_(){
-    ___X_CMD_TMP_PATH_="${___X_CMD_TMP_ROOT:-${TMPDIR%/*}}"
-    if [ "$#" -ne 0 ]; then
-        local IFS=" "; local i; for i in "$@"; do
-            i="${i#*/}"
-            ___X_CMD_TMP_PATH_="${___X_CMD_TMP_PATH_}/${i%/*}"
-        done
-    fi
-}
-
-___x_cmd_tmp_root(){
-    if [ -n "$1" ]; then
-        ___X_CMD_TMP_ROOT="$1"
-    else
-        printf "%s\n" "$___X_CMD_TMP_ROOT"
-    fi
-}
-
-___x_cmd_tmp_dir(){
-    ___x_cmd_tmp_path_ "$@" 
-    x mkdirp "$___X_CMD_TMP_PATH_"
-}
-
-___x_cmd_tmp_touch(){
-    ___x_cmd_tmp_path_ "$@" 
-    x touch "$___X_CMD_TMP_PATH_"
-}
+xrc setmain ___x_cmd_path
diff --git a/mod/pkg/latest b/mod/pkg/latest
--- a/mod/pkg/latest
+++ b/mod/pkg/latest
@@ -1,40 +1,72 @@
-# Author:       Li Junhao                   l@x-cmd.com
-# shellcheck    shell=sh disable=SC3043     # xrc
+# Author:       Li Junhao           l@x-cmd.com
+# shellcheck    shell=sh            disable=SC3043      # xrc
 
-# Section : install
-xrc param/latest
+x log init pkg
+xrc os
+___x_cmd_pkg(){
+    # ___x_cmd_pkg___which_p7zip || return
+    local op="$1"
+    case "$op" in
+        ls)                     shift; ___x_cmd_pkg_ls                    "$@" ;;      # add filter, remote, installed, ...
+        update)                 shift; ___x_cmd_pkg_update                "$@" ;;
 
-___x_cmd_install(){
-    param:dsl <<A
-subcommands:
-    ls          "list all software"
-    get         "get software installation command"
-    run         "run software installation command"
-    update      "update"
-A
-    param:run
+        version)                shift; ___x_cmd_pkg_version               "$@" ;;
+        default_version)        shift; ___x_cmd_pkg_default_version       "$@" ;;
+        ll)                     shift; ___x_cmd_pkg_ll                    "$@" ;;
 
-    if [ -z "$PARAM_SUBCMD" ]; then
-        case "$1" in
-            "")     printf "%s\n" "
-SYMPOSIS:
-    x install <software>
-    x install ls
-    x install run <software>
-    x install name"
-                    ___x_cmd_install _param_help_doc ;;
-            *)      ___x_cmd_install run "$@" ;;
-        esac
-        return 0
+        # x pkg which node=v12
+        which)                  shift; ___x_cmd_pkg_which                 "$@" ;;
+
+        # x pkg download         node=v12
+        download)               shift; ___x_cmd_pkg_download              "$@" ;;
+        install)                shift; ___x_cmd_pkg_install               "$@" ;;
+        uninstall)              shift; ___x_cmd_pkg_uninstall             "$@" ;;
+        reinstall)              shift; ___x_cmd_pkg_reinstall             "$@" ;;
+
+        # x pkg activate/deactivate  node=v12
+        activate)               shift; ___x_cmd_pkg_activate              "$@" ;;
+        deactivate)             shift; ___x_cmd_pkg_deactivate            "$@" ;;
+
+        xbin)                   shift; ___x_cmd_pkg_xbin                  "$@"          ;;
+        _smoke)                 shift; ___x_cmd_pkg__smoke                "$@"          ;;
+        ""|--help|-h)           cat "$___X_CMD_ROOT_MOD/pkg/lib/help.txt" >&2; return 0 ;;
+        _x_cmd_advise_json)     cat "$___X_CMD_ROOT_MOD/pkg/lib/pkg.advise.json"        ;;
+
+
+        *)                      pkg:error "Not found command: x pkg $1"; return 1
+    esac
+}
+
+xrc:mod:lib     pkg \
+    util                xbin                main \
+    info/ls             info/ll             info/ls_installed  \
+    mutate/download     mutate/install      mutate/activate     mutate/deactivate
+
+if ___x_cmd_is_suitable_advise_env; then
+    xrc:mod:lib pkg     advise
+fi
+
+___X_CMD_PKG_RAWPATH="$___X_CMD_ROOT_TMP/pkg/raw"
+___X_CMD_PKG_DOWNLOAD_PATH="$___X_CMD_ROOT_TMP/pkg/download"
+___X_CMD_PKG_INSTALL_PATH="$___X_CMD_ROOT_TMP/pkg/installed"
+
+x mkdirp "$___X_CMD_PKG_RAWPATH" "$___X_CMD_PKG_DOWNLOAD_PATH" "$___X_CMD_PKG_INSTALL_PATH"
+# x defineddir \
+#     ___X_CMD_PKG_RAWPATH        "$___X_CMD_ROOT_TMP/pkg/raw" \
+#     ___X_CMD_PKG_DOWNLOAD_PATH  "$___X_CMD_ROOT_TMP/pkg/download" \
+#     ___X_CMD_PKG_INSTALL_PATH   "$___X_CMD_ROOT_TMP/pkg/installed"
+
+___x_cmd_pkg__smoke(){
+    local name="${1:?Provide a candidate name}"
+
+    smokepath=$(ls "$___X_CMD_PKG_RAWPATH"/*"/$name/.x-cmd/smoke.sh") 2>/dev/null
+    if [ -f "$smokepath" ]; then
+        . "$smokepath"
+    else
+        pkg:error "Smoke file of "$name" doesn't exist"
     fi
 
-    "___x_cmd_install_$PARAM_SUBCMD" "$@"
 }
 
 
-if ___x_cmd_is_suitable_advise_env; then
-    xrc advise/latest
-    advise ___x_cmd_install "" install
-fi
-
-xrc setmain ___x_cmd_install
+xrc setmain ___x_cmd_pkg
diff --git a/mod/x-cmd/latest b/mod/x-cmd/latest
--- a/mod/x-cmd/latest
+++ b/mod/x-cmd/latest
@@ -1,40 +1,124 @@
-# Author:       Li Junhao                   l@x-cmd.com
-# shellcheck    shell=sh disable=SC3043     # xrc
+# Author:       Li Junhao   l@x-cmd.com             # xrc
+# shellcheck    shell=sh    disable=SC3043,SC1091
 
-# Section : install
-xrc param/latest
+xrc:mod:lib x-cmd glob con alias args rmrf cond util lang exe hashsum lenv tmpl spell
 
-___x_cmd_install(){
-    param:dsl <<A
-subcommands:
-    ls          "list all software"
-    get         "get software installation command"
-    run         "run software installation command"
-    update      "update"
-A
-    param:run
+# Section : x main function
+___x_cmd_main_otherwise(){
+    local subcmd="$1";  shift
 
-    if [ -z "$PARAM_SUBCMD" ]; then
-        case "$1" in
-            "")     printf "%s\n" "
-SYMPOSIS:
-    x install <software>
-    x install ls
-    x install run <software>
-    x install name"
-                    ___x_cmd_install _param_help_doc ;;
-            *)      ___x_cmd_install run "$@" ;;
-        esac
-        return 0
+    local ___x_cmd_main_otherwise_code
+
+    ___x_cmd_alias_exec ___x_cmd "$subcmd" "$@"
+    ___x_cmd_main_otherwise_code=$?
+    if [ -n "$___X_CMD_ALIAS_EXEC_EXIST" ]; then
+        return $?
     fi
 
-    "___x_cmd_install_$PARAM_SUBCMD" "$@"
+    if command -v "___x_cmd_$subcmd" 2>/dev/null 1>&2; then
+        "___x_cmd_$subcmd" "$@"
+        return
+    fi
+
+    local ___X_CMD_WHICH_ONE_RESULT
+    local ___X_CMD_WHICH_ONE_RESOURCE_TYPE
+    if ___X_CMD_NO_LOCAL=1 ___x_cmd_which_one "$subcmd" 2>/dev/null; then
+        x:debug "Executing Resource: [type=$___X_CMD_WHICH_ONE_RESOURCE_TYPE] [file=$___X_CMD_WHICH_ONE_RESULT]"
+        case "$___X_CMD_WHICH_ONE_RESOURCE_TYPE" in
+            # workspace)      ___x_cmd_exe_workspace  "$___X_CMD_WHICH_ONE_RESULT" "$@" ;;
+            local)          ___x_cmd_run_by_file                "$___X_CMD_WHICH_ONE_RESULT" "$@" ;;
+            hub|http)       ___x_cmd_run_by_file                "$___X_CMD_WHICH_ONE_RESULT" "$@" ;;
+            official)       ___x_cmd___run_with_engine xrc      "$___X_CMD_WHICH_ONE_RESULT" "$@" ;;
+        esac
+        ___x_cmd_main_otherwise_code=$?
+        x:debug "Resource Executed: [type=$___X_CMD_WHICH_ONE_RESOURCE_TYPE] [file=$___X_CMD_WHICH_ONE_RESULT] [code=$___x_cmd_main_otherwise_code]"
+        return "$___x_cmd_main_otherwise_code"
+    else
+        # TODO: If we fail to introduct from xbin. Please provide the interface, ask user for what he/she wants and whether set the alias for that module globally.
+        ___x_cmd_main_otherwise_code=$?
+        if x pkg xbin init "$subcmd"; then
+            # Introduce binmod
+            "___x_cmd_${subcmd}" "$@"
+        else
+            x:error "___x_cmd_main_otherwise(): ___x_cmd_which_one fail [code: ${___x_cmd_main_otherwise_code}]"
+            return 1
+        fi
+    fi
 }
 
+___x_cmd_alias_init ___x_cmd
+
+___x_cmd_main(){        # x:trace x     # TODO: will effect x log
+
+    local subcmd="$1"
+    case "$subcmd" in
+        log)                                    shift;  ___x_cmd_log "$@" ;;        # For efficiency
+
+        *:=)                                    shift;  ___x_cmd_varset "${subcmd%:=}" "$@" ;;
+        *=)                                     shift;  ___x_cmd_varset_without_end "${subcmd%=}" "$@" ;;
+        *=if)                                   ___x_cmd_eqifelse "$@" ;;
+        *=case)                                 ___x_cmd_eqcase "$@" ;;
+        *=join*)                                ___x_cmd___varjoin "$@" ;;
+
+        readl|rl)                               shift;  ___x_cmd_readl "$@"     ;;
+        readeval|reval)                         shift;  ___x_cmd_reval "$@"     ;;
+
+        js|node)                                shift;  ___x_cmd_node "$@"      ;;
+        js=*|node=*)                            shift;  ___X_CMD_PKG_XBIN_DEFAULT_node="${subcmd#*=}" ___x_cmd_node "$@"      ;;
+
+        python|py)                              shift;  ___x_cmd_python "$@"    ;;
+        python=*|py=*)                          shift;  ___X_CMD_PKG_XBIN_DEFAULT_python="${subcmd#*=}" ___x_cmd_python "$@"    ;;
+
+        pip|pip3)                               shift;  ___x_cmd_pip3 "$@"      ;;
+
+        sh|bash|zsh|fish|ksh|dash|ash)          shift;  ___x_cmd_shell_exec "$subcmd" "$@" ;;
+        run)                                    shift;  ___x_cmd_run_by_file "$@"       ;;
+
+        test)                                   shift;  { command -v ___x_cmd_test >/dev/null 2>&1 || xrc:mod test/latest; } && ___x_cmd_test "$@" ;;
+        login)                                  shift;  xrc hub/latest && ___x_cmd_hub login "$@" ;;
+
+        z|uz)                                           ( xrc zuz && ___x_cmd_zuz "$@" ) ;;   # zl)  ( xrc zuz && ___x_cmd_zuz_ls "$@"        ) ;;       # Using ls to replace
+        wsroot)                                 shift;  ___x_cmd_wsroot "$@" ;;
+
+        update|upgrade|clear|reinstall)         shift;  xrc update "$@" ;;
+        ""|help|-H|--help|-h)                           ___x_cmd_x_cmd_help ;;
+
+        *.wx)                                           x wx run "$@" ;;
+        :*)                                     shift;  x xdk "${subcmd#:}" "$@" ;;
+        *)                                              ___x_cmd_main_otherwise "$@" ;;
+    esac
+}
+
+___x_cmd_wsroot(){
+    if [ "${1:-.}" = . ]; then
+        local cur="$PWD"
+    else
+        cd "${1:-.}" 2>&1 && local cur="${PWD}" && cd "$OLDPWD" || return
+    fi
+
+    while [ ! "$cur" = "" ]; do
+        if [ -d "$cur/.x-cmd" ]; then
+            printf "%s\n" "$cur"
+            return 0
+        fi
+        cur=${cur%/*}
+    done
+    return 1
+}
+
+# EndSection
+
+x(){
+    ___x_cmd_main "$@"
+}
 
 if ___x_cmd_is_suitable_advise_env; then
-    xrc advise/latest
-    advise ___x_cmd_install "" install
+    command -v ___x_cmd_advise >/dev/null || xrc advise/latest
+    ___x_cmd_advise init x
 fi
 
-xrc setmain ___x_cmd_install
+xi(){
+    # TODO: xi tmux xxx == x tmux @me/xxx
+    local name="$1"; shift
+    ___x_cmd_main "@me/$name" "$@"
+}
diff --git a/mod/x-cmd/lib/util b/mod/x-cmd/lib/util
--- a/mod/x-cmd/lib/util
+++ b/mod/x-cmd/lib/util
@@ -1,121 +1,382 @@
 
-___x_cmd_install_run(){
-    param:dsl <<A
-advise:
-    #1          ___x_cmd_install_name
-options:
-    #1          "get software name list"
-A
-    param:run
 
-    local YES=
-    case "$1" in
-        -y|--yes)       YES=1; shift
-    esac
-
-    local target
-    if target="$(___x_cmd_install_get "${1:?Provide target}")"; then
-        printf "Executing command:\n> \e[32;1m%s\e[0m\n\n" "$target" >&2
-        if [ -n "$YES" ]; then
-            eval "$target"
-            return
-        fi
-
-        printf "Do you want to continue? Press y to continue, otherwise will abort: " >&2
-        local ch
-        read -r ch
-        if [ "$ch" = y ]; then
-            eval "$target"
+___x_cmd_abspath_(){
+    local target_path="${1:-Please provide path}"
+    if [ "${target_path#/}" != "${target_path}" ]; then
+        ___X_CMD_ABSPATH_RESULT="$target_path"
+    else
+        local basename="${target_path##*/}"
+        if [ "$basename" = "$target_path" ]; then
+            ___X_CMD_ABSPATH_RESULT="$PWD/$target_path"
         else
-            printf "Abort becase received non y\n" >&2
-            return 1
+            cd "${target_path%/*}" && ___X_CMD_ABSPATH_RESULT="$PWD/$basename" && cd "$OLDPWD" || return
         fi
     fi
+}
+
+___x_cmd_abspath(){
+    ___x_cmd_abspath_ "$@" && printf "%s\n" "$___X_CMD_ABSPATH_RESULT"
+    # local target_path="${1:-Please provide path}"
+    # # $(dirname "$filepath")/
+    # if [ "${target_path#/}" = "${target_path}" ]; then
+    #     printf "%s" "$(cd "$(dirname "$target_path")" && pwd)/$(basename "$target_path")"
+    # else
+    #     printf "%s" "$target_path"
+    # fi
+}
+
+___x_cmd_which_panic(){
+    local ___X_CMD_WHICH_ONE_RESULT
+    if ! ___x_cmd_which_one "$p"; then
+        printf "%s\n" "Fail to find path for $p" >&2
+        return 1
+    else
+        printf "%s\n" "$___X_CMD_WHICH_ONE_RESULT"
+    fi
+}
+
+___x_cmd_which(){
+    local p
+    for p in "$@"; do
+        ___x_cmd_which_panic || return 1
+    done
+}
+
+___x_cmd_shell_exec(){
+    local shell="${1:?Provide shell}"
     shift
-}
-
-___x_cmd_install_which(){
-    local cache="$___X_CMD_ROOT/.tmp/install/index.yml"
-    if ___x_cmd_httpget_gitx x-cmd install main index.yml "$cache" "${___X_CMD_INSTALL_WHICH_UPDATE:--}"; then
-        printf "%s" "$cache"
+    if [ -x "/bin/$shell" ]; then
+        # "/bin/$shell" $X_CMD_SRC_PATH/boot && ___x_cmd_source "$@"
+        "/bin/$shell" "$@"
+    elif [ -x "/usr/bin/$shell" ]; then
+        # "/usr/bin/$shell" $X_CMD_SRC_PATH/boot && ___x_cmd_source "$@"
+        "/usr/bin/$shell" "$@"
     else
-        return 1
+        command "$shell" "$@"
     fi
 }
 
-___x_cmd_install_ls(){
-    param:void
-    local CACHE
-
-    if ! CACHE="$(___x_cmd_install_which)"; then
-        printf "Cannot download file.\n" >&2
-        return 1
-    fi
-
-    awk -v pat="${1:-""}" "${___X_CMD_ROOT_MOD}/install/lib/ls.awk" <"$CACHE"
+___x_cmd_reval(){
+    local ___X_CMD_REVAL_CODE
+    while read -r ___X_CMD_REVAL_CODE; do
+        eval "$___X_CMD_REVAL_CODE"      # Notice: If read encountering EOF, return 1
+        [ $# -eq 0 ] || "$@"
+    done
 }
 
-___x_cmd_install_update(){
-    param:void
-    ___X_CMD_INSTALL_WHICH_UPDATE=0 ___x_cmd_install_which 1>/dev/null && printf "Update success.\n" >&2
-}
 
-___x_cmd_install_name(){
-    local CACHE
-    if ! CACHE="$(___x_cmd_install_which)"; then
-        printf "Cannot download file." >&2
-        return 1
-    fi
-    awk '
-$0!~/^[ +#]/ && NF>0 {
-    print substr($0,1,length($0)-1)
-}
-' <"$CACHE"
-}
+# f(){ seq "${1:-1000}" | while read -r aaa; do  :; done   }; time f; 1ms = 100 read
+___x_cmd_readl(){
+    local code="read -r ${1:?At least provide one argument}"; shift
+    while [ "$#" -gt 0 ]; do
+        case "$1" in
+            --)
+                shift
+                break ;;
+            *)
+                code="$code && read -r $1"
+                shift ;;
+        esac
+    done
 
-___x_cmd_install_get(){
-    param:dsl <<A
-advise:
-    #1          ___x_cmd_install_name
-options:
-    #1          "get software name list"
-A
-    param:run
-
-    local CACHE
-    if ! CACHE="$(___x_cmd_install_which)"; then
-        printf "Cannot download file." >&2
-        return 1
-    fi
-
-    local data
-    data="$(___x_cmd_install_ls "^${1:?Provide software name}$")"
-    local cmd
-    if cmd="$(printf "%s\n" "$data" | awk '
-    $1~/^>/{
-        $1="";
-        cmd=$0;
-        count = count + 1;
-    }
-    END{
-        if (count == 1) {
-            gsub(/^[ ]+/, "", cmd)
-            gsub(/[ ]+$/, "", cmd)
-            print cmd
-            exit(0)
-        } else {
-            exit(1)
-        }
-    }
-')";
-    then
-        printf "%s" "$cmd"
-        return 0
+    if [ "$#" -eq 0 ]; then
+        eval "$code"
     else
-        printf "%s\n--------\n" "Found multiple commands" >&2
-        printf "%s" "$data" >&2
-        return 1
+        while eval "$code"; do
+            ___x_cmd_eval "$@"
+        done
     fi
+}
+
+
+# testcase: . util; ___x_cmd_writeml "$t" cde  | { ___x_cmd_readml c d; echo "|$c|"; echo "$d"; }
+
+___X_CMD_MULTIPLELINE_SEP="${___X_CMD_UNSEENCHAR_003}${___X_CMD_UNSEENCHAR_002}${___X_CMD_UNSEENCHAR_005}"
+___x_cmd_readml___readone(){
+    local res
+    local line
+    while :; do
+        read -r line || return $?
+        if [ "$line" = "$___X_CMD_MULTIPLELINE_SEP" ]; then
+            eval "$1=\"\$res\""
+            return 0
+        fi
+
+        if [ -z "$res" ]; then  res="$line"
+        else                    res="$res
+$line"
+        fi
+    done
+}
+
+___x_cmd_readml(){
+    local code="___x_cmd_readml___readone ${1:?At least provide one argument}"; shift
+    while [ "$#" -gt 0 ]; do
+        case "$1" in
+            --)
+                shift
+                break ;;
+            *)
+                code="$code && ___x_cmd_readml___readone $1"
+                shift ;;
+        esac
+    done
+
+    if [ "$#" -eq 0 ]; then
+        eval "$code"
+    else
+        while eval "$code"; do
+            ___x_cmd_eval "$@"
+        done
+    fi
+}
+
+___x_cmd_writeml(){
+    if [ "$#" -eq 0 ]; then
+        cat
+        printf "\n%s\n" "$___X_CMD_MULTIPLELINE_SEP"
+    else
+        while [ $# -gt 0 ]; do
+            printf "%s\n%s\n" "$1" "$___X_CMD_MULTIPLELINE_SEP"
+            shift
+        done
+    fi
+}
+
+___x_cmd_validenvname(){
+    local IFS=_
+    eval "___x_cmd_validenvname$*___= 2>/dev/null" || return 1
+}
+
+___x_cmd___convert2second_(){
+    _1=0
+    while [ "$#" -gt 0 ]; do
+        case "$1" in
+            *s)                             _1=$(( _1 + ${1%s} )) ;;
+            *m)                             _1=$(( _1 + ${1%m} * 60 )) ;;
+            *h)                             _1=$(( _1 + ${1%h} * 3600 )) ;;
+            *d)                             _1=$(( _1 + ${1%d} * 86400 )) ;;
+            1*|2*|3*|4*|5*|6*|7*|8*|9*)     _1=$(( _1 + ${1} )) ;;
+            *)
+                printf "%s\n" "Expecting arg with optional suffix of (s)econds, (m)inutes, (h)ours, or (d)ays\n" >&2
+                return 1
+        esac
+        shift
+    done
+}
+
+___x_cmd_sleep(){
+    local _1
+    if ___x_cmd___convert2second_ "$@"; then
+        x:debug "Sleep in seconds: $_1"
+        sleep "$_1"
+    fi
+}
+
+___x_cmd_shudo(){
+    local ___CODE="
+. $___X_CMD_ROOT/.boot/boot;
+"
+    local IFS=" "
+    sudo "${SHELL}" -c "$___CODE
+$*"
+}
+
+___x_cmd_hiber(){
+    ___x_cmd_shudo "x sleep $* && pmset sleepnow"
+}
+
+# Section : help and advise.json
+___x_cmd__x_cmd_advise_json(){
+    xrc cat x-cmd/lib/x.json
+}
+
+___x_cmd_x_cmd_help(){
+    printf "x     x-bash core function.
+    Uasge:  x <subcommand> [<subcommand>...]
+    Please visit our homepage for more information: https://x-cmd.com
+" >&2;
+
+    xrc advise/lib/advise_get
+    ___x_cmd_advise_get_help "$(xrc which x-cmd/lib/x.json)"
+}
+# EndSection
+
+# Section : varset
+
+___x_cmd_varset(){
+    local _______variable_name="${1}"
+    if [ "$#" -eq 1 ]; then
+        eval printf "%s" "\"\$$_______variable_name\""
+        return
+    fi
+
+    local result
+    shift 1
+
+    local ___X_CMD_EVAL_CON_SEPERATOR
+    ___X_CMD_EVAL_CON_SEPERATOR="$(printf "\001")"
+
+    result="$("$@"; printf "${___X_CMD_EVAL_CON_SEPERATOR}")"
+    result="${result%${___X_CMD_EVAL_CON_SEPERATOR}}"
+    eval "$_______variable_name=\"\$result\""
+}
+
+___x_cmd_varset_without_end(){
+    local _______variable_name="${1}"
+    if [ "$#" -eq 1 ]; then
+        eval printf "%s" "\"\$$_______variable_name\""
+        return
+    fi
+
+    local result
+    shift 1
+    result="$("$@")"
+    eval "$_______variable_name=\"\$result\""
 }
 
 # EndSection
+
+
+# Section: until
+# x until 3/12 [ -e "file" ]
+
+___x_cmd_until_is_int(){
+    if [ "$#" -gt 0 ] && { [ "$1" -gt 0 ] || [ "$1" -le 0 ]; }; then
+        return 0
+    fi 2>/dev/null
+    return 1
+}
+
+___x_cmd_until(){
+    local ___x_cmd_until___local_interval=1
+    local ___x_cmd_until___local_timeout=1000000
+    if ___x_cmd_until_is_int "$@" 2>/dev/null; then
+        ___x_cmd_until___local_interval="$1"
+        shift
+    else
+        case "$1" in
+            */*)
+                local ___x_cmd_until___local_a="${1%%/*}"
+                local ___x_cmd_until___local_b="${1#*/}"
+                if ___x_cmd_until_is_int "$___x_cmd_until___local_a" && ___x_cmd_until_is_int "$___x_cmd_until___local_b"; then
+                    ___x_cmd_until___local_interval="$___x_cmd_until___local_a"
+                    ___x_cmd_until___local_timeout="$___x_cmd_until___local_b"
+                fi
+                shift
+        esac
+    fi
+
+    local ___x_cmd_until___local_time="$(( ___x_cmd_until___local_timeout / ___x_cmd_until___local_interval ))"
+    local ___x_cmd_until___local_rest="$(( ___x_cmd_until___local_timeout - ___x_cmd_until___local_time * ___x_cmd_until___local_interval ))"
+    local ___x_cmd_until___local_i=1
+    while [ "$___x_cmd_until___local_i" -le "$___x_cmd_until___local_time" ]
+    do
+        ___x_cmd_until___local_i=$((___x_cmd_until___local_i+1))
+        sleep "$___x_cmd_until___local_interval" || return
+        ! "$@" || return 0
+    done
+    if [ "$___x_cmd_until___local_rest" -gt 0 ]; then
+        sleep "$___x_cmd_until___local_rest" || return
+        ! "$@" || return 0
+    fi
+    return 1
+}
+# EndSection
+
+
+___x_cmd_yml2json(){
+    case "$#" in
+        0)  ___x_cmd_main yq -o json e -P ;;
+        1)  ___x_cmd_main yq -o json e -P <"$1" ;;
+        2)  ___x_cmd_main yq -o json e -P <"$1" >"$2" ;;
+        *)  x:error "Accept at most two arguments."; return 1 ;;
+        # *)  ___x_cmd_main yq -o json e -P <"$1" >"$2" ;;
+    esac
+
+}
+
+___x_cmd_y2j(){
+    ___x_cmd_yml2json "$@"
+}
+
+___x_cmd_json2yml(){
+    case "$#" in
+        0)  ___x_cmd_main yq e -P ;;
+        1)  ___x_cmd_main yq e -P <"$1" ;;
+        2)  ___x_cmd_main yq e -P <"$1" >"$2" ;;
+        *)  x:error "Accept at most two arguments."; return 1 ;;
+        # *)  ___x_cmd_main yq -o json e -P <"$1" >"$2" ;;
+    esac
+}
+
+___x_cmd_j2y(){
+    ___x_cmd_json2yml "$@"
+}
+
+___x_cmd_osc52(){
+    "$@" | tee /dev/stderr | awk -f "${___X_CMD_ROOT_MOD}/x-cmd/lib/osc52.awk"
+}
+
+___x_cmd_seq(){
+    local s="$1";   shift
+    local start=1; local end; local sep=1
+    case "$s" in
+        *:*:*:*)        ;; # fail
+        *:*:*)          start="${s%:*:*}";  end="${s#*:*:}"
+                        sep="${s#*:}";      sep="${sep%:*}"
+                        ;;
+        *:*)            start="${s%:*}";    end="${s#*:}"
+                        [ "$start" -lt "$end" ] || sep=-1
+                        ;;
+        *)              end="$s"
+                        ;;
+    esac
+
+    if [ "$#" -eq 0 ]; then
+        set -- 'printf "%s\n" "$i"'
+    fi
+
+    local i
+    if [ "$start" -lt "$end" ]; then
+        [ "$sep" -gt 0 ] || { printf "%s\n" "Expect sep > 0 but get $sep"; return 1; }
+        i="$start"; while [ "$i" -le "$end" ]; do
+            eval "$@"
+            # ___x_cmd_eval "$@"
+            i=$((i + sep))
+        done
+    else
+        [ "$sep" -lt 0 ] || { printf "%s\n" "Expect sep < 0 but get $sep"; return 1; }
+        i="$start"; while [ "$i" -ge "$end" ]; do
+            eval "$@"
+            # ___x_cmd_eval "$@"
+            i=$((i + sep))
+        done
+    fi
+
+}
+
+___x_cmd_a(){
+    alias "$@"
+    # set complete
+}
+
+
+___x_cmd_mcd(){
+    local folder="${1:?Provide folder path}"
+    if [ ! -d "$folder" ]; then
+        if [ -e "$folder" ]; then
+            x:log "File existed but not a folder: $folder"
+            return 1
+        elif ! mkdir -p "$folder"; then
+            x:log "Fail to create folder: $folder"
+            return 1
+        fi
+    fi
+
+    if ! cd "$folder"; then
+        x:log "Fail to enter into folder: $folder"
+        return 1
+    fi
+}
+
diff --git a/mod/xrc/lib/util b/mod/xrc/lib/util
--- a/mod/xrc/lib/util
+++ b/mod/xrc/lib/util
@@ -1,121 +1,197 @@
 
-___x_cmd_install_run(){
-    param:dsl <<A
-advise:
-    #1          ___x_cmd_install_name
-options:
-    #1          "get software name list"
-A
-    param:run
+___x_cmd_search_path_(){
+    local cur="${1:?Provide starting path}"
+    cd "$cur" 1>/dev/null 2>&1 && cur="$PWD" && cd "$OLDPWD" || return
 
-    local YES=
-    case "$1" in
-        -y|--yes)       YES=1; shift
-    esac
-
-    local target
-    if target="$(___x_cmd_install_get "${1:?Provide target}")"; then
-        printf "Executing command:\n> \e[32;1m%s\e[0m\n\n" "$target" >&2
-        if [ -n "$YES" ]; then
-            eval "$target"
-            return
+    local relative_filepath="${2:?Provide relative filepath}"
+    while [ ! "$cur" = "" ]; do
+        if [ -f "$cur/$relative_filepath" ]; then
+            ___X_CMD_SEARCH_PATH_RESULT="$cur"
+            return 0
         fi
+        cur=${cur%/*}
+    done
+    return 1
+}
 
-        printf "Do you want to continue? Press y to continue, otherwise will abort: " >&2
-        local ch
-        read -r ch
-        if [ "$ch" = y ]; then
-            eval "$target"
-        else
-            printf "Abort becase received non y\n" >&2
+___x_cmd_search_path(){
+    ___x_cmd_search_path_ "$@" && printf "%s" "$___X_CMD_SEARCH_PATH_RESULT"
+}
+
+___x_cmd_is_interative_tty(){
+    [ "${-#*i}" != "$-" ]
+}
+
+___x_cmd_is_suitable_advise_env(){
+    [ -n "$___X_CMD_ADVISE_ENABLE" ] && [ -n "${BASH_VERSION}${ZSH_VERSION}" ] && [ "${-#*i}" != "$-" ]
+}
+
+___x_cmd_readlink_recursive(){
+    local ___X_CMD_READLINK_RECURSIVE_
+    ___x_cmd_readlink_recursive_ "$@"
+    printf "%s\n" "$___X_CMD_READLINK_RECURSIVE_"
+}
+
+___x_cmd_definelazyloader(){
+    local funcname="${1:?Provide function name}"
+    local respath="${2:?Provide resource path}"
+    eval "$funcname(){
+        if [ \"\$___X_CMD_DEFINELAZYLOADER\" = \"$funcname\" ]; then
+            printf \"No such function [%s] in [%s]\" \"$funcname\" \"$respath\"
             return 1
         fi
-    fi
-    shift
+
+        if ! xrc $respath; then
+            printf \"Fail to xrc: %s\" \"$respath\"
+            return 1
+        fi
+
+        local ___X_CMD_DEFINELAZYLOADER=$funcname
+        $funcname \"\$@\"
+    }"
 }
 
-___x_cmd_install_which(){
-    local cache="$___X_CMD_ROOT/.tmp/install/index.yml"
-    if ___x_cmd_httpget_gitx x-cmd install main index.yml "$cache" "${___X_CMD_INSTALL_WHICH_UPDATE:--}"; then
-        printf "%s" "$cache"
-    else
-        return 1
-    fi
+# VAR   SEP    IT
+___x_cmd_trimutil(){
+    eval "
+[ -z \"\$${O}\" ] && return 1
+IT=\"\${${O}%%${SEP:-
+}*}\"
+if [ \"\${IT}\" = \"\${$O}\" ]; then
+    $O=\"\"
+else
+    $O=\"\${${O}#*${SEP:-
+}}\"
+fi
+return 0
+"
 }
 
-___x_cmd_install_ls(){
-    param:void
-    local CACHE
+# f(){
+#     local IT
+#     local SEP=,
+#     local a
+#     a="abc,cde,eft"
+#     while O=a ___x_cmd_trimutil; do
+#         printf "%s\n" "$IT"
+#     done
+# }
 
-    if ! CACHE="$(___x_cmd_install_which)"; then
-        printf "Cannot download file.\n" >&2
-        return 1
-    fi
+# f
 
-    awk -v pat="${1:-""}" "${___X_CMD_ROOT_MOD}/install/lib/ls.awk" <"$CACHE"
+___x_cmd_pidofsubshell(){
+    sh -c 'printf "%s\n" "$PPID"'
 }
 
-___x_cmd_install_update(){
-    param:void
-    ___X_CMD_INSTALL_WHICH_UPDATE=0 ___x_cmd_install_which 1>/dev/null && printf "Update success.\n" >&2
+# To prevent dash inline environment problem: just for dash
+if [ "$___X_CMD_SHELL" = dash ]; then
+    alias ___x_cmd_shift1='[ $# -gt 0 ] && shift ; '
+else
+    alias ___x_cmd_shift1="shift ; "
+fi
+
+# Section: q1 q2
+case "$___X_CMD_SHELL" in
+    bash|zsh)
+___x_cmd_q1(){
+    printf "'%s'" "${1//\'/\\\'}"
 }
 
-___x_cmd_install_name(){
-    local CACHE
-    if ! CACHE="$(___x_cmd_install_which)"; then
-        printf "Cannot download file." >&2
-        return 1
-    fi
+___x_cmd_q2(){
+    printf "\"%s\"" "${1//\"/\\\"}"
+}
+    ;;
+    *)
+___x_cmd_q1(){
     awk '
-$0!~/^[ +#]/ && NF>0 {
-    print substr($0,1,length($0)-1)
-}
-' <"$CACHE"
-}
-
-___x_cmd_install_get(){
-    param:dsl <<A
-advise:
-    #1          ___x_cmd_install_name
-options:
-    #1          "get software name list"
+BEGIN{ RS="\001"; S="'\''"; }
+{
+    gsub(S, "\\" S, $0)
+    printf(S "%s" S, $0)
+}' <<A
+$1
 A
-    param:run
+}
 
-    local CACHE
-    if ! CACHE="$(___x_cmd_install_which)"; then
-        printf "Cannot download file." >&2
-        return 1
-    fi
+___x_cmd_q2(){
+    awk '
+BEGIN{ RS="\001"; S="\""; }
+{
+    gsub(S, "\\" S, $0)
+    printf(S "%s" S, $0)
+}' <<A
+$1
+A
+}
+    ;;
+esac
+# EndSection
 
-    local data
-    data="$(___x_cmd_install_ls "^${1:?Provide software name}$")"
-    local cmd
-    if cmd="$(printf "%s\n" "$data" | awk '
-    $1~/^>/{
-        $1="";
-        cmd=$0;
-        count = count + 1;
-    }
-    END{
-        if (count == 1) {
-            gsub(/^[ ]+/, "", cmd)
-            gsub(/[ ]+$/, "", cmd)
-            print cmd
-            exit(0)
-        } else {
-            exit(1)
-        }
-    }
-')";
-    then
-        printf "%s" "$cmd"
-        return 0
+# # TODO: xrc_log +xrc
+# ___xrc_log(){
+#     local level="$1"; shift
+#     [ "$level" = debug ] && [ -z "$___X_CMD_XRC_LOG_DEBUG_MODE" ] && return
+#     printf "[%s]: %s\n" "$level" "$@" 1>&2
+# }
+
+
+___x_cmd_llist(){
+    xrc xrc/lib/llist && ___x_cmd_llist "$@" ;
+}
+
+___x_cmd_awk(){
+    xrc awk/latest && ___x_cmd_awk "$@"
+}
+
+___x_cmd_evex(){
+    if [ "$#" -lt 2 ]; then
+        eval "${1:-:}"
     else
-        printf "%s\n--------\n" "Found multiple commands" >&2
-        printf "%s" "$data" >&2
-        return 1
+        "$@"
     fi
 }
 
-# EndSection
+___x_cmd_eval(){
+    if [ "$#" -lt 2 ]; then
+        eval "${1:-:}"
+    else
+        # "$@"
+        local ___x_cmd_evex_op="$1"; shift
+        eval "$___x_cmd_evex_op" "\"\$@\""
+    fi
+}
+
+# ___x_cmd_abspath(){
+#     cd "${1:?Provide Path}" && ___X_CMD_ABSPATH="$PWD" && cd "$OLDPWD" || return
+# }
+
+
+___x_cmd_isunset(){
+    eval '[ -z "${'"${1:?Provide name}"'+1}" ] ' || return 1
+    # eval '[ -z "${'"${1:?Provide name}"'}" ] && [ -z "${'"${1}"'+1}" ] ' || return 1
+}
+
+___x_cmd_retry(){
+    local ___X_CMD_RETRY_MAX_ATTEMPT=3
+    local ___X_CMD_RETRY_INTERVAL=1
+    while true; do
+        case "$1" in
+            --)                 shift; break ;;
+            -m|--max)           shift; ___X_CMD_RETRY_MAX_ATTEMPT="$1"; shift; ;;
+            -i|--interval)      shift; ___X_CMD_RETRY_INTERVAL="$1"; shift ;;
+            *)                  break ;;
+        esac
+    done
+
+    local i=1
+    local ___X_CMD_RETRY_EXITCODE
+    while true; do
+        [ "$i" -eq 1 ] || x:warn "Retrying[${___X_CMD_RETRY_INTERVAL}s,$i/$___X_CMD_RETRY_MAX_ATTEMPT]: $*"
+        ___X_CMD_RETRY_EXITCODE=0
+        "$@" || ___X_CMD_RETRY_EXITCODE="$?"
+        [ "$___X_CMD_RETRY_EXITCODE" -ne 0 ] || return 0
+        i=$((i+1))
+        [ "$i" -le "$___X_CMD_RETRY_MAX_ATTEMPT" ] || return "$___X_CMD_RETRY_EXITCODE"
+        sleep "$___X_CMD_RETRY_INTERVAL" || return 130
+    done
+}
